### ISSUE TITLE
Replace hardcoded strings with translation method in *.tsx files

### ISSUE THREAD

**Issue by lazarnikolov94** [chakra-ui/chakra-ui-docs#10]
Prepare the static docsite strings for translation:
- [ ] Replace hardcoded strings with the `t('***')` method in all `*.txs` files
   *Check out `pages/team.tsx` line `115` to see the translation method in use*
- [ ] Add those strings in `i18n/ui.json`

**Comment by wattanx** [comment]
I'd like to work on this.
