### ISSUE TITLE
Accordion: why can't I have allowMultiple without index or defaultIndex?

### ISSUE THREAD

**Issue by hmiller020414** [chakra-ui/chakra-ui-docs#1007]
### Subject

Accordion

### Description

Hello! I would like to know why it is required to have index or defaultIndex set in order to use allowMultiple. I want to be able to open multiple accordion items at a time, but don't want any open by default. What's the explanation for this not being permitted?

**Comment by noobinthisgame** [comment]
Hey @hmiller020414 
Thanks for reaching out. Could you provide a codesandbox with an example of the stated behaviour? 
The only that I know is required is that index / defaultIndex is an array.

**Comment by nikolovlazar** [comment]
It seems that it works. I've created a CodeSandbox that uses the `allowMultiple` prop without having to set the index and everything seems okay: https://codesandbox.io/s/serene-haibt-9wl3me?file=/src/index.tsx.
