### ISSUE TITLE
The "Tooltip around disabled Button" section is outdated

### ISSUE THREAD

**Issue by CodinCat** [chakra-ui/chakra-ui-docs#1023]
### Subject

Tooltip

### Description

After https://github.com/chakra-ui/chakra-ui/pull/6653, it seems that this section is no longer true.
I don't know if I should just delete the entire section so I create an issue instead.

Also curious if this prop (`shouldWrapChildren`) still has any use.

**Comment by nikolovlazar** [comment]
Yeah, feel free to open a PR to remove that section @CodinCat! I'll also tag this with Hacktoberfest so you can participate! 🙌
