### ISSUE TITLE
Publish with source maps 🗺️ 

### ISSUE THREAD

**Issue by jasonLaster** [chakra-ui/chakra-ui-docs#103]
### Description

Hey!

I just took a look at the docs for the Tab List and noticed that source maps were off by default which made it hard to see how the demos were running in the page.

Here's a quick [replay](https://app.replay.io/recording/730e9f94-b12e-4668-a6ff-e5ec15c50d62?point=22067261655031526140568330601235857&time=9372.44081942337&hasFrames=true#) of what it looks like now. It's still possible to see what's going on, but it'd be much nicer if we had the original code to look at as well.

Happy to help if this is interesting!

**Comment by ljosberinn** [comment]
can be fixed by simply adding `productionBrowserSourceMaps: true,` to `next.config.js`

**Comment by YenTingWu** [comment]
I'll take this issue!
