### ISSUE TITLE
Add theme configuration options to the documentation

### ISSUE THREAD

**Issue by torleifhalseth** [chakra-ui/chakra-ui-docs#1032]
### Description

As a developer it would be really nice to have the theme configuration in the component documentation. Maybe it used to work, but the tab for configuration theme is now empty. 

### Problem Statement/Justification

Add speed to implementation and ease of adopting the library.

### Proposed Solution or API

Make the theme tab in doc show configuration options

**Comment by nikolovlazar** [comment]
@torleifhalseth we're working on this at the moment as part of Hacktoberfest. Thanks for raising this issue. If you're interested to contribute, [have a go at it](https://github.com/chakra-ui/chakra-ui-docs/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest)!
