### ISSUE TITLE
Theming: Accordion

### ISSUE THREAD

**Issue by nikolovlazar** [chakra-ui/chakra-ui-docs#1035]
### Subject

Accordion

### Description

Create a basic theming documentation for the `Accordion` component that showcases how you can style it.

Theming file: [Accordion theming file](https://github.com/chakra-ui/chakra-ui-docs/blob/main/content/docs/components/accordion/theming.mdx)

### Template Reference

For single part components, feel free to use the `Button` component theming doc as a template reference: [Button theming](https://github.com/chakra-ui/chakra-ui-docs/blob/main/content/docs/components/button/theming.mdx).

For multipart components, feel free to use the `Input` component theming doc as a template reference: [Input theming](https://github.com/chakra-ui/chakra-ui-docs/blob/main/content/docs/components/input/theming.mdx).

**Comment by HariVP03** [comment]
Hey! I'd love to work on this if you want. Can I be assigned this issue?
