### ISSUE TITLE
Theming: Button

### ISSUE THREAD

**Issue by nikolovlazar** [chakra-ui/chakra-ui-docs#1041]
### Subject

Button

### Description

Create a basic theming documentation for the `Button` component that showcases how you can style it.

Theming file: [Button theming file](https://github.com/chakra-ui/chakra-ui-docs/blob/main/content/docs/components/button/theming.mdx)

**Comment by dev-zaid** [comment]
Can you assign this task to me?

**Comment by nikolovlazar** [comment]
Closing this because I'm providing the `Button` component theming docs as an example
