### ISSUE TITLE
Theming: Code

### ISSUE THREAD

**Issue by nikolovlazar** [chakra-ui/chakra-ui-docs#1045]
### Subject

Code

### Description

Create a basic theming documentation for the `Code` component that showcases how you can style it.

Theming file: [Code theming file](https://github.com/chakra-ui/chakra-ui-docs/blob/main/content/docs/components/code/theming.mdx)

### Template Reference

For single part components, feel free to use the `Button` component theming doc as a template reference: [Button theming](https://github.com/chakra-ui/chakra-ui-docs/blob/main/content/docs/components/button/theming.mdx).

For multipart components, feel free to use the `Input` component theming doc as a template reference: [Input theming](https://github.com/chakra-ui/chakra-ui-docs/blob/main/content/docs/components/input/theming.mdx).

**Comment by deevo-sage** [comment]
can I be assigned this? would make it similar to  #1065

**Comment by nikolovlazar** [comment]
Sure thing @deevo-sage!

**Comment by nikolovlazar** [comment]
I've cleared the assignment. Keeping the assignment will prevent another user from contributing to it, while the assigned user might give up and not unassign themselves, resulting in a locked issue.
