### ISSUE TITLE
Theming: Input

### ISSUE THREAD

**Issue by nikolovlazar** [chakra-ui/chakra-ui-docs#1051]
### Subject

Input

### Description

Create a basic theming documentation for the `Input` component that showcases how you can style it.

Theming file: [Input theming file](https://github.com/chakra-ui/chakra-ui-docs/blob/main/content/docs/components/input/theming.mdx)

**Comment by deevo-sage** [comment]
Is this PR for improving the current one as a basic one already exists?

**Comment by nikolovlazar** [comment]
@deevo-sage it already exists, but I'll be updating that one in order to create a template / reference material for the other multipart component themes.
