### ISSUE TITLE
Theming: Menu

### ISSUE THREAD

**Issue by nikolovlazar** [chakra-ui/chakra-ui-docs#1052]
### Subject

Menu

### Description

Create a basic theming documentation for the `Menu` component that showcases how you can style it.

Theming file: [Menu theming file](https://github.com/chakra-ui/chakra-ui-docs/blob/main/content/docs/components/menu/theming.mdx)

### Template Reference

For single part components, feel free to use the `Button` component theming doc as a template reference: [Button theming](https://github.com/chakra-ui/chakra-ui-docs/blob/main/content/docs/components/button/theming.mdx).

For multipart components, feel free to use the `Input` component theming doc as a template reference: [Input theming](https://github.com/chakra-ui/chakra-ui-docs/blob/main/content/docs/components/input/theming.mdx).

**Comment by hwarnke21** [comment]
Hi @nikolovlazar, I would like to work on this issue. Would you like the format to be similar to https://chakra-ui.com/docs/components/input/theming?

**Comment by noobinthisgame** [comment]
Yes you can use this as a guideline :)

**Comment by hwarnke21** [comment]
I'm still working on this. I plan to submit the pull request today. Sorry for the delay.
