### ISSUE TITLE
Theming: Modal

### ISSUE THREAD

**Issue by nikolovlazar** [chakra-ui/chakra-ui-docs#1053]
### Subject

Modal

### Description

Create a basic theming documentation for the `Modal` component that showcases how you can style it.

Theming file: [Modal theming file](https://github.com/chakra-ui/chakra-ui-docs/blob/main/content/docs/components/modal/theming.mdx)

### Template Reference

For single part components, feel free to use the `Button` component theming doc as a template reference: [Button theming](https://github.com/chakra-ui/chakra-ui-docs/blob/main/content/docs/components/button/theming.mdx).

For multipart components, feel free to use the `Input` component theming doc as a template reference: [Input theming](https://github.com/chakra-ui/chakra-ui-docs/blob/main/content/docs/components/input/theming.mdx).

**Comment by lejara** [comment]
Hello!

May i work on this?

To be clear, you want me to add the documentation to the [Modal theming file](https://github.com/chakra-ui/chakra-ui-docs/blob/main/content/docs/components/modal/theming.mdx)

**Comment by noobinthisgame** [comment]
Yes and yes :)

**Comment by nikolovlazar** [comment]
I've cleared the assignment. Keeping the assignment will prevent another user from contributing to it, while the assigned user might give up and not unassign themselves, resulting in a locked issue.

**Comment by lejara** [comment]
Hi
I am still interested in this issue
I am actually almost finished and was expecting to do a pr today

**Comment by lejara** [comment]
okay, apologies for taking too long.

**Comment by nikolovlazar** [comment]
Don't worry @lejara! No one's in a hurry 😁
