### ISSUE TITLE
Theming: Popover

### ISSUE THREAD

**Issue by nikolovlazar** [chakra-ui/chakra-ui-docs#1080]
### Subject

Popover

### Description

Create a basic theming documentation for the `Popover` component that showcases how you can style it.

Theming file: [Popover theming file](https://github.com/chakra-ui/chakra-ui-docs/blob/main/content/docs/components/popover/theming.mdx)

### Template Reference

For single part components, feel free to use the `Button` component theming doc as a template reference: [Button theming](https://github.com/chakra-ui/chakra-ui-docs/blob/main/content/docs/components/button/theming.mdx).

For multipart components, feel free to use the `Input` component theming doc as a template reference: [Input theming](https://github.com/chakra-ui/chakra-ui-docs/blob/main/content/docs/components/input/theming.mdx).

**Comment by GKosheev** [comment]
I'll create it if no one works on it

**Comment by GKosheev** [comment]
@nikolovlazar, how do I generate code for an SVG image for describing the anatomy of the Popover? I've finished everything except that.

**Comment by nikolovlazar** [comment]
@GKosheev me and @estheragbaje are making those in Figma. Feel free to open a PR and we'll make an image for you.

**Comment by GKosheev** [comment]
@nikolovlazar, for some reason, when I commit the changes for only 2 files ```theming.mdx``` and ```popover.js```, husky runs and changes ```configs/search-meta.json``` file's IDs (5671 lines). 

I installed all the packages using ```pnpm i``` (version ```7.20.0```) on Windows. Node version is ```16.17.0```. 

Is it expected behavior, or should I do something differently to avoid auto-changes in ```search-meta.json```?

**Comment by nikolovlazar** [comment]
It's okay to push the `search-meta.json` file.
