### ISSUE TITLE
Theming: Tabs

### ISSUE THREAD

**Issue by nikolovlazar** [chakra-ui/chakra-ui-docs#1092]
### Subject

Tabs

### Description

Create a basic theming documentation for the `Tabs` component that showcases how you can style it.

Theming file: [Tabs theming file](https://github.com/chakra-ui/chakra-ui-docs/blob/main/content/docs/components/tabs/theming.mdx)

### Template Reference

For single part components, feel free to use the `Button` component theming doc as a template reference: [Button theming](https://github.com/chakra-ui/chakra-ui-docs/blob/main/content/docs/components/button/theming.mdx).

For multipart components, feel free to use the `Input` component theming doc as a template reference: [Input theming](https://github.com/chakra-ui/chakra-ui-docs/blob/main/content/docs/components/input/theming.mdx).

**Comment by hwarnke21** [comment]
Hi @nikolovlazar, I can work on this one next.
