### ISSUE TITLE
Theming: Textarea

### ISSUE THREAD

**Issue by nikolovlazar** [chakra-ui/chakra-ui-docs#1094]
### Subject

Textarea

### Description

Create a basic theming documentation for the `Textarea` component that showcases how you can style it.

Theming file: [Textarea theming file](https://github.com/chakra-ui/chakra-ui-docs/blob/main/content/docs/components/textarea/theming.mdx)

### Template Reference

For single part components, feel free to use the `Button` component theming doc as a template reference: [Button theming](https://github.com/chakra-ui/chakra-ui-docs/blob/main/content/docs/components/button/theming.mdx).

For multipart components, feel free to use the `Input` component theming doc as a template reference: [Input theming](https://github.com/chakra-ui/chakra-ui-docs/blob/main/content/docs/components/input/theming.mdx).

**Comment by nikolovlazar** [comment]
@Manoj0Marmat yes, as long as you define the file in the sandbox as that.

**Comment by Manoj0Marmat** [comment]
@nikolovlazar s s i created draft pr i'm getting some error's can you please guide me where i did wrong once i got that i will help with another themes
