### ISSUE TITLE
Theming: Drawer

### ISSUE THREAD

**Issue by nikolovlazar** [chakra-ui/chakra-ui-docs#1097]
### Subject

Drawer

### Description

Create a basic theming documentation for the `Drawer` component that showcases how you can style it.

Theming file: [Drawer theming file](https://github.com/chakra-ui/chakra-ui-docs/blob/main/content/docs/components/drawer/theming.mdx)

### Template Reference

For single part components, feel free to use the `Button` component theming doc as a template reference: [Button theming](https://github.com/chakra-ui/chakra-ui-docs/blob/main/content/docs/components/button/theming.mdx).

For multipart components, feel free to use the `Input` component theming doc as a template reference: [Input theming](https://github.com/chakra-ui/chakra-ui-docs/blob/main/content/docs/components/input/theming.mdx).

**Comment by GKosheev** [comment]
I'll make a PR.

**Comment by jrachelr** [comment]
@nikolovlazar I can get started on this
