### ISSUE TITLE
(feature): Update the resources page

### ISSUE THREAD

**Issue by lazarnikolov94** [chakra-ui/chakra-ui-docs#11]
Update the resources page with new apps/websites that have been posted in the `#🌟-showcase` channel on Discord.

Context:
- The resources page is `pages/resources.tsx`
- The data lives in `configs/resources.json`
- There are 3 types: `talks`, `videos`, and `blogs`. These are not set in stone. We can also enlist `examples` as well.

Bonus: add a link to the [Design vs Dev](https://github.com/chakra-ui/design-vs-dev) repo in the `examples` category.

**Comment by sohamsshah** [comment]
I would like to work on this 😁

**Comment by lazarnikolov94** [comment]
Hey @sohamsshah! Do you have any progress on this? If timing is bad for you, maybe I should un-assign you so someone else can take this?

**Comment by sohamsshah** [comment]
Hey, pardon for the delay. Just curious #51 seems to be solving similar purpose of this PR. If it is not, please provide more insights about the issue. Else, I will look for other suitable issues to solve!

**Comment by lazarnikolov94** [comment]
#51 is more for the mechanism of the Resources page. This one focuses on the content side. We should all be updating it as things come out, but with this task I wanted to do an initial scrape.

**Comment by sohamsshah** [comment]
Thanks for letting me know. Working on this :)

**Comment by lazarnikolov94** [comment]
> Thanks for letting me know. Working on this :)

Thanks @sohamsshah! Even if you miss anything, don't worry. Just collect as much as you can.
