### ISSUE TITLE
Menu anatomy image is blank

### ISSUE THREAD

**Issue by kelvinwelter** [chakra-ui/chakra-ui-docs#1116]
### Description

The ["Anatomy" section in the Menu theming page](https://chakra-ui.com/docs/components/menu/theming#anatomy) has an image that seems incomplete. I tried to reload the page several times and the image always loaded with blank sections.

![image](https://user-images.githubusercontent.com/37090245/195967033-d3eec23f-21aa-4c8d-88dc-16e4f68af9e2.png)

**Comment by nikolovlazar** [comment]
@kelvinwelter what browser are you using?

**Comment by kelvinwelter** [comment]
Hey @nikolovlazar I'm using Firefox 90.0

**Comment by nikolovlazar** [comment]
Got it! I'll fix it now. Thanks @kelvinwelter 🙌

**Comment by nikolovlazar** [comment]
done!
