### ISSUE TITLE
Refactor get-showcase-data.ts script to run faster

### ISSUE THREAD

**Issue by lazarnikolov94** [chakra-ui/chakra-ui-docs#113]
### Description

Currently the `get-showcase-data.ts` script runs for more than 6 hours, so GitHub automatically stops it and the action is marked as `failed`. Let's refactor the script, so it only generates images for the new links that appeared in the Awesome repo, and remove the ones we have locally in `showcase.json` but don't exist in the Awesome repo.

Idea:
- Scrape the `awesome-chakra-ui` repo and get the links
- Read the local `showcase.json`
- Find the new links (exists in `awesome-chakra-ui` repo but don't in `showcase.json`)
- Remove the deleted ones (exists in `showcase.json` but don't in `awesome-chakra-ui` repo)
- Generate images only for the new ones
- Save everything in `showcase.json`

**Comment by YenTingWu** [comment]
Hi @lazarnikolov94
