### ISSUE TITLE
How to use Icon with materialdesignicons.com

### ISSUE THREAD

**Issue by frankgrinaert** [chakra-ui/chakra-ui-docs#1139]
### Subject

Icon

### What new documentation or how-to guide would you like to see?

I'm looking for the optimal way to use the [Icon component](https://chakra-ui.com/docs/components/icon) with the [Material Design Icons](https://materialdesignicons.com/) library.

Here's the approach described in [Chakra UI documentation](https://chakra-ui.com/docs/components/icon/usage#creating-your-custom-icons) for React Icons:

```
// 1. Import
import { Icon } from '@chakra-ui/react'
import { MdSettings } from 'react-icons/md'

// 2. Use the `as` prop
<Icon as={MdSettings} />
```

However, I couldn't get this to work with [MDI](https://materialdesignicons.com/). The best I could come up with is this more convoluted approach:

```
import { Icon } from '@chakra-ui/react'
import { mdiCog } from '@mdi/js';

<Icon><path d={mdiCog} /></Icon>
```

Is there a more streamlined approach than this?

The underlying problem: `@mdi/js` is essentially just a package of strings containing the path coordinates of an svg, whereas `react-icons` generates full svg icons.

**Comment by frankgrinaert** [comment]
The following approach seems to work, using an alternate MDI package, [mdi-react](https://www.npmjs.com/package/mdi-react)

```
import { Icon } from '@chakra-ui/react';
import CogIcon from 'mdi-react/CogIcon';

<Icon as={CogIcon} />
```

**Comment by aacevski** [comment]
Hey @frankgrinaert, sorry for the late reply. I hope you resolved this, one way you can try to use it with the @mdi/js package is using the chakra factory. So it would be something like this:
```typescript
<chakra.path d={mdiCog} />
```

Here's a CodeSandbox example:
https://codesandbox.io/s/chakra-ui-with-material-design-icons-bx3r94?file=/src/index.tsx

**Comment by aacevski** [comment]
Closing this due to it being stale.
