### ISSUE TITLE
AbsoluteCenter is not Documented at all

### ISSUE THREAD

**Issue by maxswjeon** [chakra-ui/chakra-ui-docs#1147]
### Subject

AbsoluteCenter

### Description

So I found a component named `AbsoluteCenter`. Yes, it could be infered its usage by its name, but I don't know how to use it well.  
Can we document this component?

**Comment by aacevski** [comment]
This component can be documented on the `Center` component documentation.

**Comment by maxswjeon** [comment]
Closed as it finished
