### ISSUE TITLE
Add Docs Regarding NextJS v13

### ISSUE THREAD

**Issue by TylerAPfledderer** [chakra-ui/chakra-ui-docs#1169]
### Subject

NextJS v13

### Description

With the release of NextJS 13 and it's new directory structure, the docs page regarding the framework needs to be updated.

Per the [NextJS docs](https://beta.nextjs.org/docs/styling/css-in-js) Emotion is not supported for the new `app` directory structure. Therefore, this new documentation should say that you can upgrade to the new NextJS version, but stick to the previous file structure.

**Comment by felipebarcelospro** [comment]
In the last few days, I've made countless attempts to integrate Chakra UI into the new version of NextJS and I haven't been able to find a way that works 100%. So far, I managed to make it work only on Client Side.
