### ISSUE TITLE
Usage with NextJS 13's app directory

### ISSUE THREAD

**Issue by Lodimup** [chakra-ui/chakra-ui-docs#1172]
### Subject

Getting started

### Description

NextJS 13 adds a new way to structure routing with app directory
https://nextjs.org/blog/next-13#app-directory-beta

Please add a guide specifically for integrating ChakraUI for this new way of routing.

**Comment by felipebarcelospro** [comment]
In the last few days, I've made countless attempts to integrate Chakra UI into the new version of NextJS and I haven't been able to find a way that works 100%. So far, I managed to make it work only on Client Side.

**Comment by ChaitanyaLessonbee** [comment]
How did you achieve that? Any documentation? @felipebarcelospro
