### ISSUE TITLE
Styling Next.js 13 Link 

### ISSUE THREAD

**Issue by oBusk** [chakra-ui/chakra-ui-docs#1196]
### Subject

Link

### Description

There is a section about how to use with Next.js Link, 
https://chakra-ui.com/docs/components/link/usage#usage-with-nextjs

![image](https://user-images.githubusercontent.com/13413409/199372278-d9be88da-cd79-4af6-9c6e-0de73852aba7.png)

With [Next.js 13](https://nextjs.org/blog/next-13), `next/link` now outputs the `<a>` element by default. Because of this, the suggested "Usage with Next.js" is not correct anymore. You can keep the suggestion working by adding `legacyBehaviour` to the `NextLink`. 

I assume it would probably be preferred to use `as={NextLink}` if possible, but I can't get that to work.

**Comment by ChaitanyaLessonbee** [comment]
Is Chakra UI working with the `app` directory in Next.js 13 now? I couldn't get it to work.

**Comment by oBusk** [comment]
> Is Chakra UI working with the `app` directory in Next.js 13 now? I couldn't get it to work.

https://chakra-ui.com/getting-started/nextjs-guide#nextjs-13
