### ISSUE TITLE
Create a FAQ page

### ISSUE THREAD

**Issue by lazarnikolov94** [chakra-ui/chakra-ui-docs#12]
### Description

Create a FAQ page where we can answer the most commonly asked questions on Discord, Twitter or GitHub.

### Problem Statement/Justification

There are new developers getting started with Chakra UI every day. Most of them ask the same questions on Discord/Twitter/GitHub, and wait for someone to answer them. Having a FAQ page will help the newcomers progress easier and faster.

### Proposed Solution or API

Similarly to how the Resources page works, we can create `pages/faq.tsx` which will read the Q&As from `configs/faq.json`.

See `pages/resources.tsx` to see how it's implemented.

**Comment by noobinthisgame** [comment]
I'd like to work on this. (Just as note until i can assign the issue to myself)

**Comment by noobinthisgame** [comment]
@lazarnikolov94 Is there a specific way on how to generate the search-meta content for new entries for omnisearch?
