### ISSUE TITLE
Inconsistent naming of framworks with "JS" in name

### ISSUE THREAD

**Issue by givensuman** [chakra-ui/chakra-ui-docs#1214]
### Subject

Getting Started > Frameworks

### Description

The frameworks in the Getting Started section of the documentation are named inconsistently. This is a minuscule issue but just something I noticed.

[Next.js](https://chakra-ui.com/getting-started/nextjs-guide) is on the sidebar "Next JS" and in the page both "Nextjs" and "Next.js" 

This differs from, say, [Blitz.js](https://chakra-ui.com/getting-started/blitzjs-guide) which is referred to consistently as "Blitz JS" (even though their own [documentation](https://blitzjs.com/) seems to prefer "Blitz.js"), and [RedwoodJS](https://chakra-ui.com/getting-started/redwoodjs-guide) which is referred to as such, consistent with its own documentation.

Suggestion: Either make each framework consistent in Chakra, i.e. "Next JS, Blitz JS, Redwood JS", or consistent with their own documentation, i.e. "Next.js, Blitz.js, RedwoodJS"

**Comment by nikolovlazar** [comment]
Good point @givensuman! Thanks for opening this issue.

**Comment by aacevski** [comment]
I'll be taking this! 🚀
