### ISSUE TITLE
Color Mode Outdated Docs

### ISSUE THREAD

**Issue by tresorama** [chakra-ui/chakra-ui-docs#1220]
### Subject

Color Mode

### Description

Update doc page for `Color Mode` to reflect current behavior.
This issue is related to this [PR](https://github.com/chakra-ui/chakra-ui-docs/pull/1062)

## ⛳️ Current behavior (need updates)

I found hard to understand how to structure `ThemeConfig` based on my desired behavior.

Current docs suggest an outdated usage of the `Color Mode` API.
Current docs refers to Chakra v1 behavior of the Color Mode, not to v2.

Chakra v2 updated the code (as stated [here](https://github.com/chakra-ui/chakra-ui/releases/tag/%40chakra-ui%2Fcolor-mode%402.0.0) and [here](https://chakra-ui.com/getting-started/migration#breaking-changes) ) and confirmed by a [codesandbox](https://codesandbox.io/s/chakra-ui-color-mode-test-f5fcwr?file=/src/uiLayer.chakra/customTheme.ts) i created to test.

More details follow.

### `useSystemColorMode` behavior
 [This part](https://chakra-ui.com/docs/styled-system/color-mode#behavior-of-colormode) from docs is not true anymore 

<img width="744" alt="Schermata 2022-11-13 alle 10 42 07" src="https://user-images.githubusercontent.com/47954700/201515531-c7bad2b6-1c70-432f-bbc7-56895ba209ad.png">

as stated [here](https://chakra-ui.com/getting-started/migration#breaking-changes).

<img width="759" alt="Schermata 2022-11-13 alle 10 13 48" src="https://user-images.githubusercontent.com/47954700/201515492-c8546531-61aa-424c-b155-f1aebfde2c8b.png">

### `useColorMode` hook 
`useColorMode` is able to change color mode with all possible configuration of the `ThemeConfig` object, as opposed to [this sentence](https://chakra-ui.com/docs/styled-system/color-mode#behavior-of-colormode) 

<img width="544" alt="Schermata 2022-11-13 alle 10 50 26" src="https://user-images.githubusercontent.com/47954700/201515851-6bf9ac77-7940-4be6-b69b-fe017b72b628.png">

This can be tested by changing values in this [Codesandbox](https://codesandbox.io/s/chakra-ui-color-mode-test-f5fcwr?file=/src/uiLayer.chakra/customTheme.ts)

## 🚀 Proposed Changes

Help newcomers to understand current behavior and avoid confusion.

Proposed changes:
- Suggest common usages of the theme config ready to copy/paste, with the idea to remove confusion.
  - Link a playground for manual testing of theme config options.
- Add an introduction to Color Mode
- Clarify default value of theme config options.

I've started writing a new version of that page in this draft [PR](https://github.com/chakra-ui/chakra-ui-docs/pull/1062).

Is it ok to continue working on this ?

**Comment by aacevski** [comment]
Hey @tresorama thanks for creating this issue & your pull request. I will check it out ASAP and fix the mistakes in the Color Mode page. 🚀

**Comment by tresorama** [comment]
> Hey @tresorama thanks for creating this issue & your pull request. I will check it out ASAP and fix the mistakes in the Color Mode page. 🚀

Great! Thanks

**Comment by tresorama** [comment]
Merged changes in PR  https://github.com/chakra-ui/chakra-ui-docs/pull/1062
Closing this.
