### ISSUE TITLE
(docs): Move everything except Websites from Showcase into Resources

### ISSUE THREAD

**Issue by nikolovlazar** [chakra-ui/chakra-ui-docs#124]
The [Showcase](https://chakra-ui.com/showcase) page should only display Websites. Move everything except Websites into the [Resources](https://chakra-ui.com/resources) page.

Plan:
- Move everything from Resources into Awesome Chakra UI
- Fetch the Awesome Chakra UI repo and split the data
- Websites go to the `showcase.json` file
- Everything else goes to `resources.json` with the proper tags

**Comment by AnishDe12020** [comment]
Agreed, would make more sense. So the data will be fetched the the `awesome-chakra-ui` repo and the and `resources.json` file will be updated accordingly right?

P.S. - I can work on the issue if it is going to happen

**Comment by lazarnikolov94** [comment]
Awesome! Thanks @AnishDe12020! Assigned this issue to you.

**Comment by AnishDe12020** [comment]
Ok, so the resources data and the showcase data have a completely different data structure. The resources data has 2 more fields -  `tags`, and `author`. Now, I am not sure how these can be obtained from the `awesome-chakra-ui` repository as the data is unavailable. The only thing that can be done is to make the aforementioned types optional. Should I do it that way? Also is the image necessary for resources? (because the resources page currently doesn't display any images)

Also, how should I be handling the existing data for resources?

**Comment by YenTingWu** [comment]
@nikolovlazar How do we create `resource` data for now?

**Comment by nikolovlazar** [comment]
Hey sorry I didn't reply. How doable do you think it'll be if we added the `awesome-chakra-ui` links in the `resources.json` file? Keep the existing ones, just push additional ones from `awesome-chakra-ui` into it?

Regarding the Author, we can skip it (conditionally render the author label). Regarding the tag, we can add static tags, one for the group and one `awesome-chakra-ui` for example.

What do you think?

**Comment by AnishDe12020** [comment]
> Hey sorry I didn't reply. How doable do you think it'll be if we added the `awesome-chakra-ui` links in the `resources.json` file? Keep the existing ones, just push additional ones from `awesome-chakra-ui` into it?
> 
> Regarding the Author, we can skip it (conditionally render the author label). Regarding the tag, we can add static tags, one for the group and one `awesome-chakra-ui` for example.
> 
> What do you think?

Sounds quite doable. Putting the old links on should be easy enough (I guess) but i didn't get the tags part. Is it like the new ones (ones from awesome chakra ui) will have the 'awesome-chakra-ui' tag? Also, just popped into my mind, we can add the existing things in resources.json into awesome chakra ui.



PS - i am on vacation now, will probably work on it next week

**Comment by nikolovlazar** [comment]
Sounds right, @AnishDe12020! Here's the plan:
- Move everything from Resources into Awesome Chakra UI
- Fetch the Awesome Chakra UI repo and split the data
- Websites go to the `showcase.json` file
- Everything else goes to `resources.json` with the proper tags

Are you still interested in working on this issue?

**Comment by AnishDe12020** [comment]
> Sounds right, @AnishDe12020! Here's the plan:
> 
> * Move everything from Resources into Awesome Chakra UI
> * Fetch the Awesome Chakra UI repo and split the data
> * Websites go to the `showcase.json` file
> * Everything else goes to `resources.json` with the proper tags
> 
> Are you still interested in working on this issue?

Umm, I am a bit busy with other stuff now, I am unassigning myself. If I get time later on and no one else is working on it, I will do it.

**Comment by nikolovlazar** [comment]
That's okay @AnishDe12020!

**Comment by zren45** [comment]
Hi,  Can I work on this?

**Comment by zren45** [comment]
I have questions about the tags of the resources page as well. 

How are these tags selected now? Is there a list of tags to choose from？ 

for example   "Vite", "Advanced", "Theming", "v1.6"

I'm not sure how to tag data from showcase and Awesome Chakra UI

**Comment by noobinthisgame** [comment]
We have no specific system to allocate tags to resources. They mostly highlight the main topics of the resource. There is no right or wrong here :) 
Just add them as you think is fitting ;)

**Comment by nikolovlazar** [comment]
A recent refactor makes this issue redundant. We've deprecated the Awesome Chakra UI repo, and only display certain websites in the Showcase section.
