### ISSUE TITLE
Documentation for implementing `@next/font`

### ISSUE THREAD

**Issue by awilderink** [chakra-ui/chakra-ui-docs#1247]
### Subject

Nextjs

### Description

The current documentation does not provide instructions how to use the next `@next/font` with Chakra. The Next.js documentation is incompatible with Chakra UI. 

To use the new `@next/font` api with Chakra globally: 

```tsx
/* pages/_app.tsx */

import { Rubik } from '@next/font/google';

const rubik = Rubik({ subsets: ['latin'] });

const App = ({ Component, pageProps }: AppProps) => {
  <>
    <style jsx global>
      {`
        :root {
          --font-rubik: ${rubik.style.fontFamily};
        }
      `}
    </style>
    <ChakraProvider theme={theme}>
      <Component {...pageProps} />
    </ChakraProvider>
  </>
};
```

```ts
/* theme.ts */

export const theme = extendTheme(
  ...
  {
    fonts: {
      heading: 'var(--font-rubik)',
      body: 'var(--font-rubik)',
    }
  }
  ...
);

**Comment by aacevski** [comment]
Hey @awilderink, thank you for creating this issue. This can be worked on for anyone interested! 🚀

**Comment by renchris** [comment]
How do you get @next/font to work with the font weights in the default theme? I only see options for the weight variable to be of '400' '500' '700' but not of any others in between
