### ISSUE TITLE
(feature): Create a Showcase page

### ISSUE THREAD

**Issue by lazarnikolov94** [chakra-ui/chakra-ui-docs#13]
Create a Showcase page that'll display community projects that are built with Chakra UI. Use the `#🌟-showcase` channel on Discord and the [Awesome Chakra UI](https://github.com/chakra-ui/awesome-chakra-ui) repo to gather the initial data. Categorize the data entries similarly to the [Awesome Chakra UI](https://github.com/chakra-ui/awesome-chakra-ui) repo.

You can use the https://nextjs.org/showcase for inspiration.

**Comment by YenTingWu** [comment]
Can I work on this one?

**Comment by YenTingWu** [comment]
Hi @lazarnikolov94, since there is no preview image in the [Awesome Chakra UI](https://github.com/chakra-ui/awesome-chakra-ui) repo. I'd like to use [puppeteer](https://github.com/puppeteer/puppeteer) to write a script to get preview images.

Is it ok to add a new package?

**Comment by YenTingWu** [comment]
Hi @lazarnikolov94, since there is no preview image in the Awesome Chakra UI repo. I'd write script with [puppeteer](https://github.com/puppeteer/puppeteer) to get preview images if there is a website existed.

Is it ok to add a new package?

**Comment by YenTingWu** [comment]
Uh, I misclicked un-assigned
