### ISSUE TITLE
Adding of <Collapse> Component to the Component section of the documentation

### ISSUE THREAD

**Issue by Freddo1** [chakra-ui/chakra-ui-docs#1307]
### Subject

<Collapse> component 

### Description

Hey!

I was browsing through the documentation yesterday when working on making a filter group that should be collapsed down if the user chooses by clicking a button and had some trouble finding the component to use. I have a request about giving the component in question some more visibility.

Currently, the only way I found to get an example of this (in the current documentation version) is to search for Collapse in the search bar, then go under "Collapse Props" which in turn brings you to **https://chakra-ui.com/docs/components/transitions/props** and then finally click on _"Usage"_ to bring you to **https://chakra-ui.com/docs/components/transitions/usage** where the component is used in an example at the bottom of the page as such:
```
function CollapseEx() {
  const { isOpen, onToggle } = useDisclosure()

  return (
    <>
      <Button onClick={onToggle}>Click Me</Button>
      <Collapse in={isOpen} animateOpacity>
        <Box
          p='40px'
          color='white'
          mt='4'
          bg='teal.500'
          rounded='md'
          shadow='md'
        >
          <Lorem count={1} />
        </Box>
      </Collapse>
    </>
  )
}
```

Currently, it is not mentioned on top of the page it lives under either, as it states the following:
_Transitions
Chakra exports four components `Fade`, `ScaleFade`, `Slide`, and `SlideFade` to provide simple transitions._

My **_request_** is to either mention it at the top of the transitions page or better yet let it live in the **https://chakra-ui.com/docs/components** sidebar.

I reckon it should not be this hard to find it and it's valid props. Hope you take the suggestion into consideration. In general, I want to add: great work on the library, it's a treat to work with :)

**Comment by aacevski** [comment]
Hey @Freddo1, thank you for creating this issue! I agree. The `Collapse` transition should be mentioned above in the imports. This can be worked on!  🚀

**Comment by euliveiras** [comment]
hey
can you assign to me, please?
