### ISSUE TITLE
Bad Core Web Vitals

### ISSUE THREAD

**Issue by AnishDe12020** [chakra-ui/chakra-ui-docs#136]
### Description

I decided to run a lighthouse test on the Chakra UI website yesterday and I was surprised to see the scores come in quite low (in fact the performance is in the red territory)

Screenshot - 
![image](https://user-images.githubusercontent.com/63192115/146117372-f1cc02d2-a7e7-4235-b882-1f04b5ebc35d.png)

Observation 1: Use of Chakra `Img` (docs say that it should be used with SSR pages) and `chakra.img`
Fix: Replace with Next Image ( #137 )

Observation 2: Bad contrast ratio on light mode
![image](https://user-images.githubusercontent.com/63192115/146140943-1766c8df-ab07-479c-b941-d6dfcff18ab8.png)
![image](https://user-images.githubusercontent.com/63192115/146141055-f0a41a3b-6619-4bd3-908f-fdaf9d72f2e9.png)
Fix: I don't know. Chakra UI team needs to change colors to improve the contrast ratio.

Observation 3: Well, something lighthouse is complaining about, I don't understand it. I hope someone can explain this to me and there is a fix for this
![image](https://user-images.githubusercontent.com/63192115/146141290-4c5d448c-3e10-4974-adfe-9efd9ce61554.png)

Observation 4: SEO issues - 
![image](https://user-images.githubusercontent.com/63192115/146141643-43d7fcbf-beb7-4082-b2f4-642acf70aa99.png)
Awaiting response from the team on this

I have created a pr ( #137 ) for the first observation. I am not sure about the best way to approach the other ones and hence I would like to have advice from the team.

**Comment by tannguyencse19** [comment]
Lighthouse is just the [lab tools](https://web.dev/vitals-tools/). Need field tools to verify this though.

However, https://web.dev/measure/ compare between field data and lab data. And result showing that your concern maybe true.

![image](https://user-images.githubusercontent.com/62830718/146784666-20e1dbcc-01ee-4197-a53d-64fbcaeaeb99.png)

![image](https://user-images.githubusercontent.com/62830718/146784750-e19e5b79-b174-43fd-91b1-71cf98f3db5c.png)

**Comment by nikolovlazar** [comment]
Hey folks! Some time ago I pushed an update that replaced the codesandbox embed with the Sandpack package and that improved the page performance. Right now the page loading is far from bad, so for the time being I'll close this issue. If you have any ideas on how to improve the score even further, do not hesitate to hack around and open a PR. Thank you!

<img width="1059" alt="CleanShot 2022-03-11 at 08 34 31@2x" src="https://user-images.githubusercontent.com/5396211/157823528-b9a1b359-b307-4f8e-93da-d2409a81109b.png">
