### ISSUE TITLE
"Hooks" section missing from sidebar

### ISSUE THREAD

**Issue by tdukart** [chakra-ui/chakra-ui-docs#1373]
### Description

It looks like when the FIgma documentation was added, the Hooks section was removed from the sidebar. The pages still exist (https://chakra-ui.com/docs/hooks/use-checkbox), but there's no easy way to navigate to them.

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
