### ISSUE TITLE
Chakra UI + Formik example is broken

### ISSUE THREAD

**Issue by hems** [chakra-ui/chakra-ui-docs#1383]
### Description

https://chakra-ui.com/getting-started/with-formik

![image](https://user-images.githubusercontent.com/27327/214174404-ab208e95-6e23-406f-9925-f24c36fb7821.png)

**Comment by hems** [comment]
turns out after refreshing it worked?

can you reproduce?

**Comment by aacevski** [comment]
Works for me as well, I will close it, if it happens again, please create another issue.
