### ISSUE TITLE
Fix version to v1 in the install command of v1 Nextjs docs

### ISSUE THREAD

**Issue by cseas** [chakra-ui/chakra-ui-docs#1402]
### Subject

Getting Started with Nextjs

### Description

I wanted to use Chakra UI in a Next.js project with React 17 so I ended up here:
https://v1.chakra-ui.com/guides/getting-started/nextjs-guide

The install command mentioned is:

```sh
npm i @chakra-ui/react @emotion/react@^11 @emotion/styled@^11 framer-motion@^6
```

This installs Chakra UI v2. I figured out after I started getting weird errors and noticed that I had Chakra v2 installed.

The command should be changed to use `@chakra-ui/react@^1` so it installs v1.

I'd be happy to make the change but I can't find the source code of v1 docs.

**Comment by aacevski** [comment]
Good to be worked on!
