### ISSUE TITLE
Official Remix + Chakra-UI template is broken

### ISSUE THREAD

**Issue by ImExoOdeex** [chakra-ui/chakra-ui-docs#1409]
### Description

Official **[remix template](https://chakra-ui.com/getting-started/remix-guide#template)** is not working. If you open the **[sandbox](https://codesandbox.io/s/github/remix-run/examples/tree/main/chakra-ui)**, the styles will go after load. I would like to use official template.

here's video: 

https://user-images.githubusercontent.com/83508485/217382419-dee1738b-1865-49e9-8b09-89c71d947b66.mp4

**Comment by dev-phantom** [comment]
This works fine on my PC 
have you tried refreshing your browser not codesand box browser ?

**Comment by ImExoOdeex** [comment]
oh yeah, found the issue... The same problem were causing two things. 
1. Browser plugin to disable google analytics javascript.
2. Ofc I tried running in incognito mode my app, but google tag manager script was causing this bug also. (google analytics works)
So, the way to fix it, is to check dangerously set scripts in app. I think I can close it for now, since it's resolved.
