### ISSUE TITLE
(docs): Checkbox example breaking the docs mobile layout

### ISSUE THREAD

**Issue by noobinthisgame** [chakra-ui/chakra-ui-docs#142]
### Description

On the Checkbox documentation page, one example is not responsive and breaks the mobile layout of the docs. See following picture.

![image](https://user-images.githubusercontent.com/21695702/146455207-82a0d1cd-dfbf-43fb-98bc-7a4f9d48748e.png)

**Comment by bryg217** [comment]
Hello,

I can take this one, if that is okay with you.

Best,

Bryan

**Comment by bryg217** [comment]
Thanks.  🙏

**Comment by bryg217** [comment]
@nikolovlazar ,

Created PR, but I had a follow-up, on something else.

Long story short: This time around, when I tried accessing the Checkbox documentation page, I was getting an error for the `import` statement in `./pages/docs/[[...slug]].tsx`, specifically `import { allDocs } from '.contentlayer/data'`.  Essentially, I did not have `.cotentlayer` within `node_modules`.  I fixed the issue by running `contentlayer` command, `./node_modules/.bin/contentlayer build`.

Anyway, just wanted to let you know to see if it was an issue with the build itself, documentation for the build, or something I was doing wrong on my end?

Which, I originally just ran:

1. Update my fork
2. `git pull` (to get the latest from my fork)
3. `yarn` (to ensure dependencies are installed)
4. `yarn dev`

Again, to fix, I just ran the `contentlayer` build command before step `4`, above.  Also, what is interesting is that if I made an update to one of the documentation pages, in this case Checkbox, I had to re-run `contentlayer` build command.  🤔 

Let me know if there is anything else you need on my end.  If this is an issue, whether it be build process or documentation, I'd be happy to help address.

All the best.

PS: I am running Windows 10 machine on my machine.
