### ISSUE TITLE
Instructions for how to use an imported svg file with <Icon> component

### ISSUE THREAD

**Issue by nick-inkeep** [chakra-ui/chakra-ui-docs#1458]
### Subject

Icon

### Description

The examples used for https://chakra-ui.com/docs/components/icon/usage#using-the-createicon-function don't show how to use imported svg files.

The 'recommendation' says how to export icons as svg from Figma/Sketch, but does not provide guidance on how one would use that svg.

**Comment by noobinthisgame** [comment]
Hi @nick-inkeep, 

the recommendation is meant as an alternative to the `createIcon` function. You can easily use your own svg like this https://github.com/chakra-ui/chakra-ui-docs/blob/main/src/components/logo.tsx with Chakra UI.

Closing this for now. Let me know if this was helpful :)
