### ISSUE TITLE
Example for  `<ChakraProvider> ` &  `<CacheProvider>` in Next.js 13 is wrong in docs 

### ISSUE THREAD

**Issue by jinojacob15** [chakra-ui/chakra-ui-docs#1476]
### Subject

 <ChakraProvider>  <CacheProvider> is wrongly placed in chakra ui docs for next js 13 

### Description

Below is the image of doc of chakra ui as on 16-March,2023

![DeepinScreenshot_select-area_20230316194318](https://user-images.githubusercontent.com/69616951/225644959-bc40faf7-9205-4a65-bb62-28523eece64a.png)

and Below in docs of beta next js docs as on 16th March ,2023 

![DeepinScreenshot_select-area_20230316194736](https://user-images.githubusercontent.com/69616951/225645526-568d62ad-e54c-459a-9596-d58231d52a11.png)

For third party context providers , Next js suggests like this way 
![DeepinScreenshot_select-area_20230316194950](https://user-images.githubusercontent.com/69616951/225647343-0e2067f9-eac1-4d83-92c0-b4c1b4137bc5.png)

**Main Point is that we cannot make app/layout.js file as  client component** 

@ryanahamilton @curdin  @

**Comment by noobinthisgame** [comment]
@jinojacob15 thanks for opening this issue. Feel free to open a PR wirh your solution :)

**Comment by jinojacob15** [comment]
@noobinthisgame  how to open a PR . Can u elaborate

**Comment by noobinthisgame** [comment]
We have a [guide](https://chakra-ui.com/getting-started/contributing) about contributing. Make sure to read it. Let me know if you need help :)

**Comment by jinojacob15** [comment]
@noobinthisgame  , please can u do it for me , I am afraid ,I may end up wrong .  @noobinthisgame  dont need any credits , I am happy I cud help

**Comment by jinojacob15** [comment]
@noobinthisgame   still chakra docs are not updated

**Comment by noobinthisgame** [comment]
Hey @jinojacob15, we are all working on this for free in our free time. We can't takle everything at the same time. If this is really important to you feel free to open a PR 🙂 
Thanks for understanding.

**Comment by jinojacob15** [comment]
@noobinthisgame  ok . Please take your time
