### ISSUE TITLE
Is it against copyright to use images from Japanese animation?

### ISSUE THREAD

**Issue by ytetsuro** [chakra-ui/chakra-ui-docs#1495]
### Description

I am wondering if the images used in the following document have copyright permission.
I strongly believe that it is probably best to use a safe image that has no copyright issues.
Unless this library is copyrighted by Shueisha.

https://github.com/chakra-ui/chakra-ui-docs/blob/33fbcde40e359e91af3aa7825b8e81929bbab2ae/content/docs/components/tabs/usage.mdx#make-a-tab-initially-active

**Comment by segunadebayo** [comment]
Since we don't download the images locally and use them on the website. The images only link to the external source.

There should be no issues with Copyright but thanks for bringing this up.

**Comment by ytetsuro** [comment]
@segunadebayo 

Thanks your response!

> The images only link to the external source.

The following wiki is a case that became a bit of a social phenomenon in the past in Japan.

https://en.wikipedia.org/wiki/Mangamura

The administrator of this site similarly argued that it was not a copyright violation because he was only posting a link to the image.
The administrator lived outside of Japan but was sentenced to prison in Japan as a result of this incident.

I hope this triviality does not affect the chakra UI community.

**Comment by ishowta** [comment]
At least the referenced image is clearly illegally uploaded, which does not make a good impression.
