### ISSUE TITLE
Parameters of useDisclosure hook are not documented

### ISSUE THREAD

**Issue by gauravsoni119** [chakra-ui/chakra-ui-docs#1540]
### Description

When I am looking into the [parameter](https://chakra-ui.com/docs/hooks/use-disclosure#parameters) section of `useDisclosure` hook, I am not able to see any table for the parameters. After the line: _**The useDisclosure hook accepts an optional object with the following properties:**_ nothing is there. 
As a user, I am expecting parameter names with descriptions and their default value.

| Parameter | Type | Description |
|--------|--------|--------|
| isOpen (Optional) | boolean | If true, the controlled component is responsible for changing the visible state via `onClose` and `onOpen` props.  |
| defaultIsOpen (Optional) | boolean | If `true`,  it sets the controlled component to its visible state|
| onClose | function | Function to set a falsy value for the isOpen parameter. |
| onOpen | function | Function to set a truthy value for the isOpen parameter. | 

If accepted, I am happy to contribute.:)

**Comment by aacevski** [comment]
Hey @gauravsoni119, this looks good to be worked on! You can go ahead.
