### ISSUE TITLE
Document Stack Component Margin and Padding Behavior on Siblings

### ISSUE THREAD

**Issue by tophermurphy** [chakra-ui/chakra-ui-docs#1560]
### Subject

Stack

### Description

Referencing issue https://github.com/chakra-ui/chakra-ui/issues/2578

Please document the behavior in the Stack component of the sibling child elements having the top and bottom margin and padding set to 0.

> Margins not working due to *:not(style)~*:not(style)

Not here to argue about the behavior. It would just be nice to have a heads up in the docs.

**Comment by segunadebayo** [comment]
This doesn’t apply anymore as the latest versions of Chakra updated its components to use flex gap.
