### ISSUE TITLE
Add elements inside Input example component error

### ISSUE THREAD

**Issue by scooby359** [chakra-ui/chakra-ui-docs#1569]
### Description

When visiting the Add elements inside section of the Input docs, the example component is broken.

Expected to see an input component with a left element. Instead, it displays an error:

```
SyntaxError: Expected corresponding JSX closing tag for <InputLeftElement> (7:2)
3 :     <InputLeftElement pointerEvents='none'>
4 :       <PhoneIcon color='gray.300' />
5 :     <InputLeftElement/>
6 :     <Input type='tel' placeholder='Phone number' />
7 :   </InputGroup>
      ^
```

In the code, the slash appears to be in the wrong place for the closing tag of InputLeftElement.

https://chakra-ui.com/docs/components/input/usage#add-elements-inside-input

**Comment by noobinthisgame** [comment]
Thanks for reporting this has been closed with #1578 :)
