### ISSUE TITLE
Color Mode Feature - Add ColorModeScript Next.js of TypeScript version

### ISSUE THREAD

**Issue by tannguyencse19** [chakra-ui/chakra-ui-docs#164]
### Subject

Color Mode

### Description

In `chakra-ui` source code has the `ColorModeScript` of Next.js in TypeScript version. 

The docs don't have, which cause confusion because `theme.ts` already had .js and .ts version + People are using TypeScript more and more nowadays.

```tsx
export default class Document extends NextDocument {
  static getInitialProps(ctx: DocumentContext) {
    return NextDocument.getInitialProps(ctx)
  }

  render() {
    return (
      <Html>
        <Head />
        <body>
          <ColorModeScript />
          <Main />
          <NextScript />
        </body>
      </Html>
    )
  }
}
```

**Comment by nikolovlazar** [comment]
Hi @tannguyencse19. Recently we've made a docsite restructure and made sure to add this in the Next.js guide here: https://chakra-ui.com/guides/getting-started/nextjs-guide#color-mode-script. Thank you for opening this issue.
