### ISSUE TITLE
Syntax Error on Toast Usage Page

### ISSUE THREAD

**Issue by Goldfish7718** [chakra-ui/chakra-ui-docs#1660]
### Subject

Unexpected token on Promise Based Toast Documentation

### Description

<img width="494" alt="image" src="https://github.com/chakra-ui/chakra-ui-docs/assets/111229457/d6768bfa-c763-4ac9-ad87-a2f180cb2464">

Apparently, There seems to be an unexpected token somewhere around the return statement that is not editable in the given window. You can reproduce this by removing all the code and still seeing the error.

**Comment by mingjunlu** [comment]
I've created a PR to fix this (#1663) 😃
