### ISSUE TITLE
docs(popover): Enabled prop in documentation should not be exposed

### ISSUE THREAD

**Issue by StuartReeve** [chakra-ui/chakra-ui-docs#183]
### Subject

Popover

### Description

In the documentation for the Popover component, it explains that enabled is available and it would toggle whether the popper.js popover should be enabled. 

This comment on another issue related to this suggests it should not be documented:
https://github.com/chakra-ui/chakra-ui/issues/5155#issuecomment-984784300

The enabled prop should be removed from the Popover documentation.

**Comment by nikolovlazar** [comment]
Exactly! Are you interested in opening a PR for this, @StuartReeve?

**Comment by StuartReeve** [comment]
@nikolovlazar Sure I can open a PR for this. I haven't contributed to this project before, is there anything special that needs doing?
