### ISSUE TITLE
docs(framer-motion): Update "Chakra UI + Framer Motion" integration guide's examples to use the "chakra" factory + "as" prop

### ISSUE THREAD

**Issue by tannguyencse19** [chakra-ui/chakra-ui-docs#192]
### Subject

Code example

### Description

Why don't use like this?

```jsx
<Box as={motion.div} />
```

**_Cons_**: `chakra` props will be prioritized over `framer-motion` props if existing prop that have the same name. e.g:

```jsx
<Box 
    as={motion.div} 
    transition="all 0.5s linear" 
   /* not: 
   transition={
        duration: 0.5,
        ease: "linear"
   }
   */
/>
```

**Comment by noobinthisgame** [comment]
Hi @tannguyencse19, could you elaborate on this? To continue further here we need more details on what you are missing and what/where things have to change in the docs.

**Comment by nikolovlazar** [comment]
@noobinthisgame I think @tannguyencse19 has a point. The docs utilize the `motion` factory function, which has changed over the time and it's throwing an error now. We could utilize the `chakra` factory function, just like we do when wrapping the Next.js Image component. Here's a codesandbox that implements the two ways: https://codesandbox.io/s/eager-estrela-wwg3k4?file=/src/index.tsx. The behaviour is the same, but there's an error in the `motion` way. I guess we should update the docs to use the `chakra` factory function instead.

**Comment by wattanx** [comment]
I'd like to work on this!

**Comment by tannguyencse19** [comment]
> @noobinthisgame I think @tannguyencse19 has a point. The docs utilize the `motion` factory function, which has changed over the time and it's throwing an error now. We could utilize the `chakra` factory function, just like we do when wrapping the Next.js Image component. Here's a codesandbox that implements Framer Motion in three different ways: https://codesandbox.io/s/eager-estrela-wwg3k4?file=/src/index.tsx. The behaviour is the same, but there's an error in the `motion` factory function way. I guess we should update the docs to use the `chakra` factory function and the `as` prop instead:
> 
> ```ts
> // `chakra` factory function
> const ChakraBox = chakra(motion.div, {
>   shouldForwardProp: isValidMotionProp
> });
> ```
> 
> or
> 
> ```js
> // `as` prop
> <Box
>    as={motion.div}
>    height="40px"
>    width="40px"
>    bg="orange.400"
>    drag="x"
>    dragConstraints={{ left: -100, right: 100 }}
>    whileHover={{ scale: 1.1 }}
>    whileTap={{ scale: 0.9 }}
> />
> ```

This is the first time I saw other people give argument that support my idea. It means a lot to me. 

Thanks for expressing my idea in detail.
