### ISSUE TITLE
`backdropBlur` not working?

### ISSUE THREAD

**Issue by Calvein** [chakra-ui/chakra-ui-docs#210]
### Description

When I try to use the `backdropBlur` style prop, it doesn't work

### Link to Reproduction

https://codesandbox.io/s/elated-bell-668t4?file=/src/index.js

### Steps to reproduce

Those props all add the css var `--chakra-backdrop-blur: blur(6px)` to the element but not `background-filter`;

```
backdropBlur="6px"
sx={{ backdropBlur: "6px" }}
__css={{ backdropBlur: "6px" }}
```

Setting the filter directly worked though.
```
css={{ backdropFilter: "blur(6px)" }}
```

### Chakra UI Version

1.7.4

### Browser

Chrome 96

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

The only reference I found of `backdropBlur` in the documentation was in this changelog https://chakra-ui.com/changelog#17-05-2021

PS: Is there a better way to "transparentize" a color that in my example?
```js
const theme = useTheme();
const bg = transparentize(theme.colors.gray[800], 0.8)(useTheme());
```

**Comment by Calvein** [comment]
It makes sense, thanks @TimKolberger.

**Comment by sohamsshah** [comment]
I would like to work on this. Any insights what could be the best place to put this piece of documentation?

**Comment by nikolovlazar** [comment]
@sohamsshah I think the Style Props page would make sense for now. We don't have a section for filters, so this is a good opportunity to expand on it. You can use the Flexbox section as an inspiration:
<img width="824" alt="CleanShot 2022-01-27 at 11 44 43@2x" src="https://user-images.githubusercontent.com/5396211/151343976-0c3392ec-040d-4af5-8967-fbf3f7b4f37d.png">

**Comment by joerush18** [comment]
sx={{
        filter: "blur(4px)",
}}
You can use it as above:
