### ISSUE TITLE
Update Remix + Chakra documentation

### ISSUE THREAD

**Issue by primos63** [chakra-ui/chakra-ui-docs#220]
### Subject

Integrate Chakra with Remix

### Description

The documentation for using Chakra UI with Remix needs to be updated. There are changes to server-side and client-side code to prevent the loss of styles.

My Github repo contains the [source code](https://github.com/primos63/chakra-remix-example) for a working example application.

**Comment by noobinthisgame** [comment]
See this issues comment https://github.com/chakra-ui/chakra-ui/issues/5166#issuecomment-1058354976

Seems like the content of the repo is not working with newer Remix versions
