### ISSUE TITLE
Latest Version of framer-motion broken  in latest version of CRA

### ISSUE THREAD

**Issue by Umoren** [chakra-ui/chakra-ui-docs#252]
### Subject

Framer motion

### Description

From the [Getting Started](https://chakra-ui.com/docs/getting-started) page, `framer-motion` was included in the dependencies. But it seems the latest version has path issues in current version of CRA. You often get this error `./node_modules/framer-motion/dist/es/components/AnimatePresence/index.mjs
Can't import the named export 'Children' from non EcmaScript module (only default export is available)`

This has been fixed in the latest version of CRA (still in alpha)
but to fix this for folks having this issue, you just need to downgrade to version*4.1.17* `npm i framer-motion@4.1.17`. 
So maybe you could update the documentation to reflect this for folks having this issue

**Comment by nikolovlazar** [comment]
Hi @Umoren. I tried to replicate this issue with `framer-motion` v6, but I didn't get this error, maybe they fixed it in v6. Let me know if the issue still happens. If not, feel free to close this issue.
