### ISSUE TITLE
@chakra-ui/gatsby-plugin docs isn't related to Gatsby

### ISSUE THREAD

**Issue by Chuloo** [chakra-ui/chakra-ui-docs#274]
### Description

In the guide here https://chakra-ui.com/guides/getting-started/gatsby-guide, the section containing information on extending the default theme isn't clear. 
In gatsby, there isn't an `<App />` component but rather `element` exposed through the `wrapRootElement` API in gatsby-browser.js. Hence, the demo relates to general React use cases instead of gatsby.js. 

I'm presently finding it difficult to add custom themes as different texts point out different ways to do this, that don't seem to work.

**Comment by nikolovlazar** [comment]
Hi @Chuloo! I don't have any experience with Gatsby, but judging by their docsite you might be right. I can see that there's a `gatsby-browser.js` file that has the following code block:
```typescript
// Wraps every page in a component
exports.wrapPageElement = ({ element, props }) => {
  return <Layout {...props}>{element}</Layout>
}
```

It seems like this might be the right place to inject Chakra UI into Gatsby, but as I mentioned, I have zero experience with Gatsby.

If you have a good experience with Gatsby, I'm encouraging you to open a PR that fixes the guide. If you need any help getting in doing that, don't hesitate to reach out. I'd be glad to assist you.
