### ISSUE TITLE
docs(contribution): Update Contribution guide

### ISSUE THREAD

**Issue by aboveyunhai** [chakra-ui/chakra-ui-docs#281]
### Subject

documentation

### Description

https://chakra-ui.com/docs/contributing#docs-contribution

Previously I check this doc and download the main repo. 
Of course, there is not such a script `npm run docs:start` to run doc until I realized that the doc is moved to its own repo.

Maybe worth rewriting this part of doc now for the correct location of doc repo?

**Comment by noobinthisgame** [comment]
Yeah it seems like this hasn't been updated in a while. Think it's a good idea to give it a refresh :)
