### ISSUE TITLE
Incorrect comment in margin and padding style props

### ISSUE THREAD

**Issue by Bradzer** [chakra-ui/chakra-ui-docs#290]
### Subject

Style props

### Description

The  example of the margin and padding example in the style props documentation [here](https://chakra-ui.com/docs/features/style-props#margin-and-padding) seems wrong.

I think `<Box m={[2, 3]} />` sets margin `8px` on all viewports and **`12px`** from the first breakpoint and up and **_not_**  **`16px`** as stated in the example.

**Comment by m4x3d** [comment]
You are right. `3` is with the default theme 0.75rem or 12px as described in https://chakra-ui.com/docs/theming/theme#spacing.

Thanks for reporting this typo. ;)
