### ISSUE TITLE
docs: mobile view for the contribution page is broken

### ISSUE THREAD

**Issue by noobinthisgame** [chakra-ui/chakra-ui-docs#309]
### Description

Some parts of the [docs contribution page](https://chakra-ui.com/docs/contributing) are not responsive enough to be shown on phones.

**Comment by nikolovlazar** [comment]
@noobinthisgame which parts exactly? I can see the GitHub Token Settings URL is breaking in a weird way. Is there anything else you had in mind?

**Comment by noobinthisgame** [comment]
Hmm I can't seem to reproduce this either. I'll close this.
