### ISSUE TITLE
Can't Resolve '.contentlayer/data'

### ISSUE THREAD

**Issue by TylerAPfledderer** [chakra-ui/chakra-ui-docs#318]
### Description

I am looking to contribute to the Chakra Documentation, though I am running into the following error when spinning up the local server and attempt to navigate to any documentation page (Or selecting "Get Started" link on the landing page):
```bash
wait  - compiling /_error (client and server)...
error - ./pages/docs/[[...slug]].tsx:1:0
Module not found: Can't resolve '.contentlayer/data'
> 1 | import { allDocs } from '.contentlayer/data'
  2 | import type { Doc } from '.contentlayer/types'
  3 | import { MDXComponents } from 'components/mdx-components'
  4 | import { GetStaticPaths, GetStaticProps } from 'next'
```

The following steps to reach to this error:
1. Fork `chakra-ui/chakra-ui-docs`
2. Clone the fork to local
3. Run `yarn` to install dependecies
4. Run `yarn dev` to run local server
5. Select the "Get Started " link on the landing page or query to a doc page in the address bar (i.e. `http://localhost:3000/docs/disclosure/accordion`)

I am noticing that both `.contentlayer/data` and `.contentlayer/types` show empty exports.

Also, the `CONTRIBUTION` files at the root and in the `docs` folder do not appear to be consistent in how to set up the local space for a PR.

**Comment by nikolovlazar** [comment]
Hello @TylerAPfledderer! I can't seem to reproduce this issue. Did you try removing the `node_modules` and `.contentlayer` folders and running the `yarn` command again? Also, what version of node are you using?

**Comment by TylerAPfledderer** [comment]
Hello, @nikolovlazar !

Node `v17.4.0`

If there was a `.contentlayer` folder that was supposed to appear on install that is not the one in `node_modules` then it never appeared.

I removed `node_modules` and ran `yarn` again. No change.

**Comment by nikolovlazar** [comment]
I tried updating to Node 17 (17.5.0 to be precise), removed `.contentlayer` and `node_modules`, ran `yarn` and then `yarn dev` and everything seems to work fine. You should see something like this in the logs:
```
info  - Disabled SWC as replacement for Babel because of custom Babel configuration ".babelrc" https://nextjs.org/docs/messages/swc-disabled
event - compiled client and server successfully in 2.3s (641 modules)
Generated 113 documents in node_modules/.contentlayer
```

Contentlayer creates its folder when you do `yarn`, but kicks in when you do `yarn dev`.

Can you provide more details regarding your dev environment? (os, yarn version, etc...)

**Comment by TylerAPfledderer** [comment]
Ok!

So with the dev environment, aside from Node:
- Windows 10 `v.10.0.19043.1526`
- yarn `v1.22.5`

Yea, the two files generated in `node_modules/.contentlayer` which are `data` and `types` show empty export objects.

I can certainly update Node to 17.5.0 and try again!

**Comment by TylerAPfledderer** [comment]
Updated Node to v`17.5.0`, removed `node_modules` and ran `yarn` again.

Here is the complete log in the command line when I run `yarn dev` and then attempt to navigate to the docs via the "Get Started" button link:

```bash
$ yarn dev
yarn run v1.22.5
$ next
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
warn  - The `target` config is deprecated and will be removed in a future version.
See more info here https://nextjs.org/docs/messages/deprecated-target-config
warn  - You have enabled experimental feature(s).
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.

info  - Disabled SWC as replacement for Babel because of custom Babel configuration ".babelrc" https://nextjs.org/docs/messages/swc-disabled
info  - Using external babel configuration from C:\Users\tyler\Documents\Sites\chakra-ui-docs\.babelrc
event - compiled client and server successfully in 8s (641 modules)
wait  - compiling / (client and server)...
event - compiled client and server successfully in 12.9s (2259 modules)
error - uncaughtException: Error: ENOENT: no such file or directory, open 'C:\Users\tyler\Documents\Sites\chakra-ui-docs\.next\cache\images\Nvj0gu9d6bT8htUZSP+ZZiQbkmtvJtDpFGwgLVWqrvg=\0.1644779504286.sqS9-nUkdI76ftelOb9qRmP8qbuTK8pHfEFYSptZQg4=.webp'
wait  - compiling /docs/[[...slug]]...
event - compiled client and server successfully in 667 ms (2115 modules)
wait  - compiling /docs/[[...slug]] (client and server)...
error - ./pages/docs/[[...slug]].tsx:1:0
Module not found: Can't resolve '.contentlayer/data'
> 1 | import { allDocs } from '.contentlayer/data'
  2 | import type { Doc } from '.contentlayer/types'
  3 | import { MDXComponents } from 'components/mdx-components'
  4 | import { GetStaticPaths, GetStaticProps } from 'next'

https://nextjs.org/docs/messages/module-not-found
wait  - compiling /_error (client and server)...
error - ./pages/docs/[[...slug]].tsx:1:0
Module not found: Can't resolve '.contentlayer/data'
> 1 | import { allDocs } from '.contentlayer/data'
  2 | import type { Doc } from '.contentlayer/types'
  3 | import { MDXComponents } from 'components/mdx-components'
  4 | import { GetStaticPaths, GetStaticProps } from 'next'

https://nextjs.org/docs/messages/module-not-found
```

**Comment by nikolovlazar** [comment]
@TylerAPfledderer can you try running `npx contentlayer build` and see what happens?

**Comment by TylerAPfledderer** [comment]
```bash
$ npx contentlayer build
Warning: Contentlayer might not work as expected on Windows
Generated 113 documents in node_modules/.contentlayer
```

Ran `yarn dev` and the docs are now successfully rendering. Thank you!
