### ISSUE TITLE
docs(style-props): Make Filter examples live and editable

### ISSUE THREAD

**Issue by nikolovlazar** [chakra-ui/chakra-ui-docs#319]
### Subject

Style Props

### Description

Make the Filter examples in the [Style Props](https://chakra-ui.com/docs/features/style-props#filter) page live and editable. This would include providing a bit more rich examples in which you can see the effect of the filter props.

**Comment by TylerAPfledderer** [comment]
Hey @nikolovlazar!

May I attempt to update this section?

**Comment by nikolovlazar** [comment]
Sounds good, @TylerAPfledderer!
