### ISSUE TITLE
Search on Chakra site is broken

### ISSUE THREAD

**Issue by sgehrman** [chakra-ui/chakra-ui-docs#348]
### Description

search broken

### Link to Reproduction

https://what.com

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Chakra UI Version

1.6.8

### Browser

chrome

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

### Additional Information

Uncaught TypeError: Cannot read properties of undefined (reading 'url')
    at omni-search.tsx:187:39
    at Object.$e (react-dom.production.min.js:52:317)
    at Ye (react-dom.production.min.js:52:471)
    at react-dom.production.min.js:53:35
    at xr (react-dom.production.min.js:100:68)
    at Cr (react-dom.production.min.js:101:380)
    at react-dom.production.min.js:113:65
    at Fe (react-dom.production.min.js:292:189)
    at react-dom.production.min.js:50:57

**Comment by noobinthisgame** [comment]
@sgehrman Thanks for opening this issue. It would be awesome if you could provide more informations about how to reproduce this next time :)

@m4x3d I managed to reproduce the described error. It can be done by typing something random until no more options are shown in the search and hitting enter. The error will show in the browsers developer console. This issue doesn't seem to have a direct impact on the behaviour of the search nor on the usage of the docs in general. So no users should be really impacted by this bug.
