### ISSUE TITLE
Remove flags from language switcher

### ISSUE THREAD

**Issue by lazarnikolov94** [chakra-ui/chakra-ui-docs#35]
### Description

Remove the flag from the Language Switcher component and replace it with a generic language icon.

Reasons:
https://www.thirdandgrove.com/insights/should-you-use-flags-for-your-country-language-selector-menu/
http://www.flagsarenotlanguages.com/blog/best-practice-for-presenting-languages/

**Comment by YenTingWu** [comment]
I will work on this one!
