### ISSUE TITLE
Changelog long mdx code components are not responsive on mobile

### ISSUE THREAD

**Issue by noobinthisgame** [chakra-ui/chakra-ui-docs#358]
### Description

On the changelog page the very long mdx code components are not responsive on mobile. This is caused by the whiteSpace property in the theme.ts (mdx.code) beeing set to nowrap. Removing this doesn't resolve the issue as it's set on purpose because code components should be in one piece. 

To solve this issue it is needed to find a way to make only the very long mdx code components responsive without breaking the current behaviour of the code components.

![Screenshot 2022-02-25 at 23 53 50](https://user-images.githubusercontent.com/21695702/155813806-7a488195-7d14-4f9e-8671-911f9377d678.png)

**Comment by TylerAPfledderer** [comment]
Hey @noobinthisgame!

Could a conditional be used in the `InlineCode` component, where we attach a ref to it and check against a certain width of the component by saying something like `ref.current.offsetWidth > <value>`?

I'm thinking of this:

```jsx
export const InlineCode = (props: any) => {
  const codeRef = useRef(null)
  return (
    <chakra.code
      apply='mdx.code'
      color={useColorModeValue('purple.500', 'purple.200')}
      ref={codeRef}
      whiteSpace={codeRef.current.offsetwidth > 363 && 'normal'}
      {...props}
    />
  )
}
```

**Comment by TylerAPfledderer** [comment]
Hey @noobinthisgame !

Maybe apply a ref to the `InlineCode` component and run a ternary against `offsetWidth`?

I'm think of this:
```jsx
export const InlineCode = (props: any) => {
  const codeRef = useRef(null)
  return (
    <chakra.code
      apply='mdx.code'
      color={useColorModeValue('purple.500', 'purple.200')}
      ref={codeRef}
      whiteSpace={codeRef.current.offsetWidth > 363 ? 'break-spaces' : 'nowrap'}
      {...props}
    />
  )
}
```

The value `363` comes from the minimum width of the `li` element on the changelog page before the layout shifts to mobile.
