### ISSUE TITLE
Using Radio with Formik

### ISSUE THREAD

**Issue by maxskewes** [chakra-ui/chakra-ui-docs#374]
### Subject

Using Radio with Formik, and images as Radio

### Description

Chakra touts its compatibility with Formik, yet the documentation is not there to provide it. Searching the site is incredibly difficult as there is simply no documentation for the majority of Chakra's features (example: search: 'useRadioGroup', a hook provided by Chakra. Results = nil). Radio and Checkboxes are notoriously difficult to make compatible, and it would be an extreme help if there were a page for each's compatibility with Formik. In addition, part of that page should be designated on how to use images as radio buttons. I know Chakra has some info on how to use boxes as radio inputs (good luck finding it on the site though :) ), but as the hooks and their props are incredibly unintuitive, extremely proprietary, difficult to adapt and unrelated to the methods of other libraries or HTML, further documentation is absolutely necessary before Chakra can claim compatibility with Formik. It is hard on devs when UX designers see that Chakra claims compatibility, hence recommending Chakra, only for the dev to find that the documentation simply doesn't exist. Please dedicate more time to documentation on the unique method that must be employed to allow these libraries to work together, and if they simply cannot - then please make that explicit on the site.

**Comment by nikolovlazar** [comment]
Closing this. #448 will fix this issue.
