### ISSUE TITLE
Chakra CLI usage with postinstall script is incorrect

### ISSUE THREAD

**Issue by TheAsda** [chakra-ui/chakra-ui-docs#380]
### Subject

Advanced Theming

### Description

In documentation it is said that you can specify `postinstall` script and it'll regen theme typings.
<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/35863331/156432478-814f36c6-958a-4b46-8231-fe6f64d1747f.png)
</details>

This won't work if you are publishing it as UI library as `@chakra-ui/cli` is specified in dev dependencies. So i think it's going to be fair to change this part a bit and specify how to deal with theme typing generation when using it in library. 

<details>
<summary>P.S.</summary>

I don't thing that it is useful to regen typings every time you add a dependency to your library. So this part of documentation, in my opinion, is pretty useless for now.
</details>

**Comment by noobinthisgame** [comment]
Hey @TheAsda! 
Thanks for your feedback. 
The postinstall regeneration of the types is needed when you add a new dependency as the old generated types get deleted during every install process.

Concerning the publication of the theme as a package, please refer to [this part](https://chakra-ui.com/docs/styled-system/theming/advanced#distributing-a-theme-package) of the docs. You will need to provide the users of your theme package with a guide on how to setup their own script to generate the typings from your theme with the `@chakra-ui/cli`.

I hope this helps! Feel free to close this issue if it did 😊

**Comment by TheAsda** [comment]
Ok, got it!
