### ISSUE TITLE
Outdated/confusing docs for setting Container maxWidth in theme.sizes.container

### ISSUE THREAD

**Issue by webwelten** [chakra-ui/chakra-ui-docs#401]
### Subject

component

### Description

I must admit that I'm a little confused what's the best way/best practice to use the Container. 
In the Container docs it says:

> By default, it sets the max-width of the content to 60 characters (60ch) but you can customize this by passing custom maxWidth values **or changing the container size tokens defined in theme.sizes.container**

First of all: I've never been in a project that used the character size as maxWidth (although I can see how it makes sense). Often frameworks would offer maxWidth values for certain breakpoints instead (like bootstrap etc. for example) or in projects we would follow the designers guidelines. Do you have a different experience? What's the reason behind this default? (I am just curious. As long as I can adapt it, I'm fine with this being the default)

> you can customize this by passing custom maxWidth values **or changing the container size tokens defined in theme.sizes.container**

This sounds to me that changing **theme.sizes.container** would adapt every Container I use. But instead it just changes what I can reference in maxW, right? I find that part a little confusing and I think that adapting maxW everytime is more an exception. I would expect that the docs provide a best practice for the global option and only then describes how to adapt certain cases.

As far as I know my use case can be solved like that:

```
components: {
  Container: {
    baseStyle: {
      maxWidth: […]
    }
  }
}
```

Did you get my point? Any other perspectives or other ways your using Container?

**Comment by noobinthisgame** [comment]
Hey @webwelten ! 
I don't know what exactly was the reasoning behind the default value (maybe @segunadebayo can give you more insights about that). In any case the maxWidth in the `Container` is adjustable for your needs and use cases.

Overriding the values of the `theme.sizes.container` in your custom theme, changes the value of the tokens used in the maxWidth props as in this [example](https://chakra-ui.com/docs/components/layout/container#container-size). This would be my preferred approach You can find the default values in this file: https://github.com/chakra-ui/chakra-ui/blob/main/packages/theme/src/foundations/sizes.ts#L23 

Your solution of changing the theme for the `Container` through a custom theme is also a valid way to address those changes. 

Feel free to raise a PR with improvement to the docs. 😊🚀

**Comment by TylerAPfledderer** [comment]
I can comment that the default value of `60ch` is the common approach to the best readability of a single column of text on desktop (a range of 45-75 characters per line, to be more precise).

You have to keep in mind though that this unit is based on the width of the character `0` which depends on the typeface used. Maybe it depends on context if this creates undesirable results when using more than one column?

Maybe this article could help with a sensible implementation of the unit, should you want to use it: 
https://webflow.com/feature/control-width-of-text-elements-by-character-count-using-ch-unit

**Comment by TylerAPfledderer** [comment]
@noobinthisgame checking back in on this.

It's been a while now since this issue was posted. I can open a PR, as the details in the docs about the `maxWidth` are at the top of the page when they could be better placed with the [Container Size](https://chakra-ui.com/docs/components/layout/container#container-size) section. And can link back to the [Sizes Default Theme](https://chakra-ui.com/docs/components/layout/container#container-size) section in reference the container size token.
