### ISSUE TITLE
(docs): add recipe for advanced Formik integration with Chakra UI

### ISSUE THREAD

**Issue by noobinthisgame** [chakra-ui/chakra-ui-docs#407]
### Subject

Recipe 

### Description

As discussed in https://github.com/chakra-ui/chakra-ui-docs/issues/374 a nice improvement would be a detailed recipe on how to integrate Formik with custom components and more advanced forms.

For that a new recipe page in the components section would be really nice.

**Comment by aacevski** [comment]
I can take this.
