### ISSUE TITLE
docs(maintainers): Create a section in Team for former maintainers

### ISSUE THREAD

**Issue by nikolovlazar** [chakra-ui/chakra-ui-docs#430]
The main `chakra-ui` repo has a [HALL_OF_MAINTAINERS.md](https://github.com/chakra-ui/chakra-ui/blob/main/HALL_OF_MAINTAINERS.md) file which lists all of the former maintainers that used to work on Chakra UI. We should get the contents of that file and list the former maintainers in the Teams page under the "Core team" section.

You can use the [`scripts/get-showcase-data.ts`](https://github.com/chakra-ui/chakra-ui-docs/blob/main/scripts/get-showcase-data.ts#L133-L154) to see how you can fetch the file contents of another github repo. Create something similar for the `HALL_OF_MAINTAINERS.md` file that sits in the main `chakra-ui` repo.

**Comment by aaronmcadam** [comment]
Can I have this issue please? 😄
