### ISSUE TITLE
Search Meta for changelog page renders 'changelog/content' instead of 'changelog

### ISSUE THREAD

**Issue by TylerAPfledderer** [chakra-ui/chakra-ui-docs#437]
### Description

When I search for the `changelog` page in the website's searchbar, it navigates to a url with the subdirectory `/changelog/content` which doesn't exist and renders a 404 page. This is also consistent when searching for a specific changelog date (i.e. `/changelog/content#28-02-2022`)

The subdirectories should be `/changelog` and `/changelog#28-02-2022` respectively, and so on.

**Comment by noobinthisgame** [comment]
Hey @TylerAPfledderer,

@nikolovlazar has already been working on a fic for this :) 

https://github.com/chakra-ui/chakra-ui-docs/pull/423

**Comment by TylerAPfledderer** [comment]
Oops! I need to slow down. 😅 Thank you for mentioning it @noobinthisgame
