### ISSUE TITLE
Add Docs for the `TableContainer` component

### ISSUE THREAD

**Issue by noobinthisgame** [chakra-ui/chakra-ui-docs#447]
### Subject

Table

### Description

Chakra UI provides a `TableContainer` component to manage table responsiveness (https://github.com/chakra-ui/chakra-ui/blob/main/packages/table/src/table.tsx). 

In docs this component is missing. It would be nice to have it documented.

**Comment by TylerAPfledderer** [comment]
@noobinthisgame I can work on this!
