### ISSUE TITLE
(docs): add clarification to the `Stack` doc details/examples

### ISSUE THREAD

**Issue by TylerAPfledderer** [chakra-ui/chakra-ui-docs#465]
### Subject

Stack

### Description

There are a couple of sections in the [`Stack` Component Docs](https://chakra-ui.com/docs/components/layout/stack) showing arguably redundant, incorrect, and/or confusing information.

- Section ["Stack Items Horizontally"](https://chakra-ui.com/docs/components/layout/stack#stack-items-horizontally): 
  - The details talk about using the `direction` prop, but the example uses the `HStack` component. This might also be a redundant section as it is currently being presented. 
  - Possible consideration would be to remove those contradicting details, and redoing the structure of the page so that this example is shown as part of a group with [the previous example](https://chakra-ui.com/docs/components/layout/stack) under a new header like `Use Case Examples`
```
### Use Case Examples
  #### Feature Cards with Stack Component
  #### Feature Cards with HStack Component
```

- Section ["Notes on Stack vs Flex"](https://chakra-ui.com/docs/components/layout/stack): 
  - The details here are not accurate and seem to be unfinished in providing a quality comparison. Combining `Stack` and `Flex` (I guess this means `<Stack as={Flex}>` or vice versa) does not allow you to alter spacing of any one child component -- via `margin`, say -- as that change will still be overwritten by the styling from `Stack`. You can use the `Spacer` component though to add spacing to the value provided by `Stack`.
  -  `justifyContent` is a valid prop for both components so it's not clear as to the purpose in including it in the explanation. 
  - Possible considerations are to remove this detail, and either referencing the `Flex` section ["Flex and Spacer vs Grid vs Stack"](https://chakra-ui.com/docs/components/layout/flex#flex-and-spacer-vs-grid-vs-stack), creating a more clear note in the `Stack` doc, or provide more clarity in both sections in the `Stack` and `Flex` docs to better articulate the differences.

Some other areas of this page may or may not provide enough or clear information, but the points above stuck out the most. I appreciate any thoughts to my observations. 😄

**Comment by nikolovlazar** [comment]
It makes sense, @TylerAPfledderer. I think it's a good idea to refresh the content on the Stack component. I've marked this issue as a "Good first issue" so anyone can participate in fixing it.

**Comment by aacevski** [comment]
@nikolovlazar can I take this? 🙌
