### ISSUE TITLE
ci: automate the changelog and version bump

### ISSUE THREAD

**Issue by segunadebayo** [chakra-ui/chakra-ui-docs#481]
### Description

We need to figure out a way to automate these steps when a new Chakra UI package is released:

- Bump the version of `@chakra-ui/react`
- Run `yarn changelog:gen` to fetch the most recent changelog from the
  [main repository](https://github.com/chakra-ui/chakra-ui)
- Open a Pull Request titled `docs: updates for new release`

**Comment by aacevski** [comment]
Regarding this, @segunadebayo I'd say we setup a cron job, let's say every hour which checks if the current version of Chakra is the same with the one on npm. I'm not sure about the: Bump the version of `@chakra-ui/react`, wouldn't generating the changelog do that itself?

**Comment by noobinthisgame** [comment]
I read about this topic, there should be a away with github actions to trigger actions in this repo from the main repo. So whenever we run a release we can trigger actions here to create a new pr.

https://github.community/t/triggering-by-other-repository/16163

**Comment by aacevski** [comment]
I'd like to take this and I'll use this method!

**Comment by segunadebayo** [comment]
Great idea @noobinthisgame! Thanks for sharing that.

@aacevski, go for it!
