### ISSUE TITLE
Add warning labels to components that use MediaQueries to conditionally render content.

### ISSUE THREAD

**Issue by mix3d** [chakra-ui/chakra-ui-docs#504]
### Subject

Visibility, Show, Hide, Others?

### Description

I just shot myself in the foot with the <Show>/<Hide> components and SSR, leading to some strange behavior and cryptic error messages. I think a warning box in the docs might help prevent someone else from unwittingly doing the same.

The useMediaQuery SEEMS like it's supposed to check for isBrowser, but I still got strange behavior when working with a Salesforce PWAKit application. The issue is probably because the server says "Not a browser, I don't have media queries, so I default to false / render `null`", but the browser gets the same code and says "uhh, I'm supposed to render on this screen size", which leads to a mismatch in SSR vs Browser.

**Comment by noobinthisgame** [comment]
@mix3d Documentation changes are welcome here :) We are trying our best to work on all issues but we are doing this in our free time ;) Feel free to open a PR and contribute this to the documentation :)

**Comment by mix3d** [comment]
Was mostly concerned about the stalebot... I've had bad experiences in other repos where legitimate issues get auto closed save swept under the rug before they can be addressed.
