### ISSUE TITLE
(feature): Refactor the Resources page

### ISSUE THREAD

**Issue by lazarnikolov94** [chakra-ui/chakra-ui-docs#51]
### Subject

Resources

### Description

Refactor the Resources page.

- Isolate the Talks, Videos and Blogs into their own tabs.
- Add a search filtering functionality inside the tabs.
- ⭐️ Bonus challenge: Utilize a masonry grid to display the resources.

**Comment by bryg217** [comment]
Hey @lazarnikolov94 ,

Hope all is well.

I'd like to take on this one, if it is still available.  Let me know if I can be designated as the assignee.

All the best,

Bryan

**Comment by lazarnikolov94** [comment]
Sure @bryg217!

**Comment by lazarnikolov94** [comment]
@bryg217 I think it'd be simple enough to do everything in 1 PR.
