### ISSUE TITLE
White flicker in dark mode

### ISSUE THREAD

**Issue by prkagrawal** [chakra-ui/chakra-ui-docs#517]
### Description

When I selected dark mode and reloaded the page, there was a brief moment of white screen flicker.

**Comment by TylerAPfledderer** [comment]
Hey @prkagrawal!

This is a known issue and the team made a statement on the [Color Mode Docs Page](https://chakra-ui.com/docs/styled-system/features/color-mode#color-mode-flash-issue)

**Comment by noobinthisgame** [comment]
Thanks @prkagrawal for opening an issue but this issue can't be solved in the docs. As @TylerAPfledderer mentioned this is an implementation specific behaviour. Closing this issue :)
