### ISSUE TITLE
docs(alert): Usage example - close button and content overlap on mobile

### ISSUE THREAD

**Issue by TylerAPfledderer** [chakra-ui/chakra-ui-docs#522]
### Description

Currently, when view the first [`Alert` example](https://chakra-ui.com/docs/components/feedback/alert#usage) on certain mobile screens the `CloseButton` overlaps the alert description container, which can be visually broken depending on the text supplied at specific sizes.

At `467px` wide screen:
![image](https://user-images.githubusercontent.com/65234762/162773400-01492324-d76c-43bc-86ee-5fd80a5db11d.png)

### Possible Solution
The `CloseButton` is separate in it's styling from the `Alert` so it would still need to be directly positioned. Firstly, remove all the styling given in the current example so the button is back within the flow of the other content. At larger screen sizes, we can leverage the flexbox supplied by the alert container and set `marginLeft: auto` to keep the button flush to the right from the content, and apply `alignSelf: flex-start` to keep it in the upper corner.

Also with a minor tweak in total spacing, you would get this:
```jsx
<Alert status='error' gap={1}>
  <AlertIcon />
  <AlertTitle mr={2}>Your browser is outdated!</AlertTitle>
  <AlertDescription>Your Chakra experience may be degraded.</AlertDescription>
  <CloseButton alignSelf="flex-start" marginLeft="auto"/>
</Alert>
```

However, if you were to view at the smallest common phone width of `375px` you'll see this:
![image](https://user-images.githubusercontent.com/65234762/162779277-5ceba02e-43e7-42d5-a3a3-9e0600e1a1b3.png)

Which isn't much different than how the current example looks at this size.

Was the alert ever meant to be styled like this with this small screen size in mind? With the `CloseButton` used in other components like `Modal` or `Drawer` there isn't this issue because the title text is always vertically stacked with the description or content and the `CloseButton` is always out of the way.

**Comment by noobinthisgame** [comment]
Hey @TylerAPfledderer, this looks like the `Alert` component has been following another pattern then others using the `CloseButton`.  It would be a question for the main repo or you could raise a PR to address responsiveness if you like to :) 
For the docs I'd go with your solution, which looks pretty decent and way better than overlapping text.

**Comment by TylerAPfledderer** [comment]
Thank you @noobinthisgame ! I will work on doing both tasks you suggested. 🤘

**Comment by TylerAPfledderer** [comment]
@noobinthisgame after reviewing the rest of the docs and taking a look at the stories in the package, it is better to simply remove the close button. From what I would gather, it is not considered "basic usage" to include the close button, but rather in a custom composition as it is already shown in the [second composition example](https://chakra-ui.com/docs/components/feedback/alert#composition).

And in that second example, it would be better to show how the close button should close the alert, rather than be shown as a static component.

It seems to me that `Alert` was meant to be more customizable than the other notification or feedback components like Modal or Alert Dialog.

**Comment by noobinthisgame** [comment]
@TylerAPfledderer Sounds good to me :)
