### ISSUE TITLE
Forward children when using chakra factory with framer-motion

### ISSUE THREAD

**Issue by desiprisg** [chakra-ui/chakra-ui-docs#541]
### Subject

Chakra UI + Framer Motion

### Description

It seems that `isValidMotionProp` does not take `children` into account. Since a motionized `Box` is used in the example, it would be  fitting to also add the `children` in the  `shouldForwardProp` function or add a notice for this.

**Comment by TylerAPfledderer** [comment]
I can grab this.

Can include `children` in `shouldForwardProp` and add a comment. All other Chakra props that don't match in `isValidMotionProp` can still be used in the component.
