### ISSUE TITLE
Use of <Global> without css``

### ISSUE THREAD

**Issue by rossmawd** [chakra-ui/chakra-ui-docs#545]
### Subject

Using Fonts Documentation

### Description

Hi, 

On this page of the docs: https://chakra-ui.com/docs/styled-system/recipes/using-fonts#option-2-using-font-face

You have 

```
const Fonts = () => (
  <Global
    styles={`
      /* latin */
      @font-face { ...
```

This does not work for me. I have to add Emotion's css method for it to work:

```
 styles={css`
        @font-face {
```

**Comment by noobinthisgame** [comment]
Hey @rossmawd,
this works as expected for me. Check out this csb example https://codesandbox.io/s/mystifying-dirac-cgl5gz?file=/src/index.tsx

Closing this issue.
