### ISSUE TITLE
(toast docs): Add docs for new containerStyle feature

### ISSUE THREAD

**Issue by segunadebayo** [chakra-ui/chakra-ui-docs#56]
### Subject

Toast

### Description

https://github.com/chakra-ui/chakra-ui/pull/4922

**Comment by YenTingWu** [comment]
I'd like to work on this issue!

**Comment by lazarnikolov94** [comment]
Assigned this to you @YenTingWu. Thanks a lot!

**Comment by YenTingWu** [comment]
Hi @segunadebayo, I can't use this feature in the latest version. Should I close the pr first and reopen it after this feature available?
