### ISSUE TITLE
[useDisclosure hook] getButtonProps and getDisclosureProps are not documented

### ISSUE THREAD

**Issue by morellodev** [chakra-ui/chakra-ui-docs#563]
### Subject

useDisclosure

### Description

The `getButtonProps` and `getDisclosureProps` functions returned by the `useDisclosure` hook are not mentioned in the documentation, neither are they used in any code example. This is a pity, since they are quite handy :rocket:

Can you add some documentation on them with examples on how they could be used?

Thanks!

**Comment by TylerAPfledderer** [comment]
Good call-out @morellodev, I agree! I would like to take this, unless you would like to make a PR. 😀

**Comment by TylerAPfledderer** [comment]
As I am looking at the source code, I noticed that `getButtonProps` returns `aria-expanded: "true"` when maybe the value should be `isOpen`?

**Comment by morellodev** [comment]
> As I am looking at the source code, I noticed that `getButtonProps` returns `aria-expanded: "true"` when maybe the value should be `isOpen`?

According to the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-expanded#buttons) you are right 👍

**Comment by TylerAPfledderer** [comment]
Yes.

And I believe these helpers would be fine in tandem if you needed simple, accessible toggling, and use the other methods for more control.

**Comment by morellodev** [comment]
PR here https://github.com/chakra-ui/chakra-ui/pull/5940

**Comment by TylerAPfledderer** [comment]
I'm going to go ahead and work on a PR to prevent this issue from going stale, and go from there with any review or additional input. 😄 

Because these getter methods return specific values, handlers, and state to be passed to a button and the affected component, they can be presented as the "starting point" in the use of this hook, and then discuss the other return props for more refined control.

**Comment by morellodev** [comment]
@TylerAPfledderer thank you a lot!

**Comment by TylerAPfledderer** [comment]
@morellodev I just now noticed that you created a PR against the `next` branch when it should also be against the `main` branch, so that the docs update correctly.

**Comment by noobinthisgame** [comment]
@TylerAPfledderer We are not merging against `main` anymore. Everything goes into next until v2 is released. Merging it into `next` ist fine, docs will update accordingly once we merge `next` into `main`. If you ment the main repository.

**Comment by TylerAPfledderer** [comment]
Ahh. Thanks @noobinthisgame! That's really good to know. 😄

**Comment by noobinthisgame** [comment]
Closed by #568
