### ISSUE TITLE
Use swc instead of babel

### ISSUE THREAD

**Issue by noobinthisgame** [chakra-ui/chakra-ui-docs#582]
### Description

Check if we can replace babel with swc to build our docs page (the default for nextjs)

Before doing so it has to be checked:
- Is emotion supported 
- Do we need superjson
- Are there other breaking things

**Comment by TylerAPfledderer** [comment]
Found this closed issue regarding [SWC and superjson](https://github.com/blitz-js/superjson/issues/157)

**Comment by noobinthisgame** [comment]
Yeah I stubled upon it aswell. The thing is with contentlayer I think we don't need superjson anymore. So no need to have a swc plugin for it.
