### ISSUE TITLE
(docs): Getting started with Remix

### ISSUE THREAD

**Issue by noobinthisgame** [chakra-ui/chakra-ui-docs#63]
### Subject

Getting Started

### Description

Now that [Remix](https://remix.run/docs/en/v1) is open sourced I think it would make sense to create a section to get started started with Remix and Chakra UI.

**Comment by lazarnikolov94** [comment]
Oh moat definitely! I plan on playing around with Remix this weekend, might jot down some guides.

**Comment by noobinthisgame** [comment]
Was planning to do so aswell. Really exiting stuff happening there 😁
I also think chakra UI and remix are sharing a similar philosophy
