### ISSUE TITLE
docs(packages): Get rid of imagemin

### ISSUE THREAD

**Issue by nikolovlazar** [chakra-ui/chakra-ui-docs#634]
### Description

The `imagemin` package causes build issues when updated to the latest `8.0.1` version. The package itself is unmaintained, plus we don't actually use its functionality.

Check out `scripts/image-cache.ts` on line `74`. The `imagemin` method is being used only if `this.compress` is true, which it actually never is.

On the other hand, we're using `next/image`, so the compression is handled that way.

**Comment by segunadebayo** [comment]
Good point. We should get rid of that package
