### ISSUE TITLE
Redesign navigation bar

### ISSUE THREAD

**Issue by segunadebayo** [chakra-ui/chakra-ui-docs#641]
### Subject

Redesign navigation bar

### Description

Given that we're starting to have more content (e.g. Tutorials, Component Theming, Case studies), I think the website's navigation needs a redesign to make it easier to find relevant content.

I think the search button takes up a lot of useful space. We should consider adding more links to the top-level navigation and provide "secondary" navigation depending on the page you're on. I'll share some examples shortly.

We've got too many links in the docs sidebar that could be added to the primary or secondary navigation links.

**Comment by nikolovlazar** [comment]
This will be solved by an upcoming major docsite redesign that we're currently working on.
