### ISSUE TITLE
Element “style” not allowed as child of element “div” in this context.

### ISSUE THREAD

**Issue by nbouvrette** [chakra-ui/chakra-ui-docs#644]
### Description

When I use the W3C validator I expect to get no errors but there are many errors with misplaced "style" elements

### Link to Reproduction

https://validator.w3.org/nu/?doc=https%3A%2F%2Fchakra-ui.com%2F

### Steps to reproduce

1. Go to https://validator.w3.org/nu/?doc=https%3A%2F%2Fchakra-ui.com%2F
2. Click check the `Element “style” not allowed as child of element “div” in this context.`

### Chakra UI Version

Latest

### Browser

Not applicable

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

As per https://github.com/validator/validator/issues/489, using `<style>` tags outside `<head>` is not following the HTML5 specifications.

There is a risk that by not following the HTML5 specifications, SEO can be impacted (see https://www.elegantthemes.com/blog/wordpress/how-to-use-w3c-validator-to-improve-seo)

As per Emotion's documentation, it looks like it is possible to move the `<style>` tag inside the `<head>`: https://emotion.sh/docs/ssr#nextjs

**Comment by dube25** [comment]
@segunadebayo : watching this issue.
Is there a timeline on a fix from Chakra-UI?

Thanks!

**Comment by TylerAPfledderer** [comment]
This is coming from the imported static font assets in [_document.tsx](https://github.com/chakra-ui/chakra-ui-docs/blob/main/pages/_document.tsx#L20-L26). The `link` element gets handled correctly on render, but indeed emotion is adding a JS bundle style inside the `body`.

Per some digging though, there is already a [FontFace](https://github.com/chakra-ui/chakra-ui-docs/blob/main/src/components/font-face.tsx) component that looks to be importing these fonts in [_app.tsx](https://github.com/chakra-ui/chakra-ui-docs/blob/main/pages/_app.tsx#L34). Simply removing the link in `_document.tsx` does not change the rendering of this font, and will subsequently remove the rendered bundle that is causing this validation error. Running a build also does show an impact of the rendering of this font.

Does the link import need to be there in `_document.tsx`?

**Comment by nbouvrette** [comment]
@TylerAPfledderer just to clarify, I opened this issue using chakra-ui.com as an example but this impacts anyone using Chakra-UI. It looks overall like Chakra's implementation of Emotions is not following the documentation found here https://emotion.sh/docs/ssr#nextjs

**Comment by TylerAPfledderer** [comment]
Agreed. What's missing is the inclusion of the server and css packages.

@nikolovlazar and/or @segunadebayo has this been addressed previously?

**Comment by segunadebayo** [comment]
Let me try to explain what's happening here:

With our current setup and approach, during SSR, emotion will render `style` tags inline as a sibling of any Chakra component. After hydration, emotion will move the styles to the head as fast as it can to prevent FOUC (flash of unstyled content)

If we implemented the SSR setup recommended by emotion docs, we'll skip that hydration step and extract all the styles to the head ahead of time. I think we should attempt to do this within our docs @nikolovlazar @TylerAPfledderer. If we notice improvements from this, we'll update our documentation to reflect this.

When you use markup validators, they'll run against the SSR output of the website and will see inline `style` as invalid, when in fact, that's not the full story.

**Comment by nikolovlazar** [comment]
I did some testing (used [this example](https://github.com/vercel/next.js/tree/deprecated-main/examples/with-emotion-vanilla)), but the style tags are still prepended before each element. Will have this issue on mind, but for now I think we can close this issue since it's related to how Emotion works.

**Comment by nbouvrette** [comment]
@nikolovlazar @segunadebayo @TylerAPfledderer hey guys, I just did a test using the same example (`npx create-next-app --example with-emotion-vanilla with-emotion-vanilla-app`) - I don't see any inline style tags?

Do you mind elaborating on what you did exactly? If I a missing something I want to open an issue on the Emotion repo.

**Comment by nikolovlazar** [comment]
@nbouvrette mark a page to use SSR, open it and open the "Page Source" (not Inspect Element). You'll see `style` tags sprinkled around the page:
![image](https://user-images.githubusercontent.com/5396211/172055726-d4088684-24ad-41b3-8cf4-f2333ea7a803.png)

**Comment by nbouvrette** [comment]
@nikolovlazar I've already validated the **source** in W3C, also beautified the output, and do not see any inline style. 

What do you mean by `mark a page to use SSR` - Next.js uses SSR everywhere

I do see the CSS in the `<head>` element.

**Comment by nikolovlazar** [comment]
@nbouvrette make sure to use `useServerSideProps` in your page. That marks that page to use SSR.

**Comment by nbouvrette** [comment]
Oh ok @nikolovlazar I thought you were talking about the rendered HTML, sorry about that.

But I did try to add the following code in the example's `index.js`:

```js
export async function getServerSideProps(context) {
  return {
    props: {}, // will be passed to the page component as props
  };
}
```

I am getting the same result in the source code - CSS inside the `<head>` element - what am I missing?

**Comment by nikolovlazar** [comment]
@nbouvrette do you have any components inside of your page? Try reproducing this with codesandbox or stackblitz and share it with me so I can take a better look.

**Comment by nbouvrette** [comment]
@nikolovlazar I was just using the vanilla example (`npx create-next-app --example with-emotion-vanilla with-emotion-vanilla-app`) - I can try to create components to see if this changes anything.

**Comment by nikolovlazar** [comment]
Yeah please do. The `style` tags that we're talking about come from the components themselves. If there are no components, no `style` tags will be present. Add various stuff on that page and check it out again. The screenshot I sent above is from Chakra UI's `index` page.

**Comment by nbouvrette** [comment]
I just tried adding a`Footer` component and I still can't reproduce the inline style - the example code can be found here:

https://github.com/nbouvrette/emotion-inline-css-issue

I'm not too sure what else to try unless you have ideas?

**Comment by nbouvrette** [comment]
@nikolovlazar by the way can we re-open this issue until we pinpoint the root cause? It's still not clear to me what is causing this

**Comment by nbouvrette** [comment]
FYI I tried to re-add all the different style types into the component to see if it was not a specific Emotion feature that triggered the issue and the CSS was still not inline.

@nikolovlazar @segunadebayo @TylerAPfledderer could we please re-open this issue and if you have any suggestions on how to try to reproduce it in this repo: https://github.com/nbouvrette/emotion-inline-css-issue

**Comment by nbouvrette** [comment]
@nikolovlazar @segunadebayo @TylerAPfledderer any ideas on how I could try to reproduce this in my repo? I might have time to investigate this weekend if you guys can give me some pointer on what could be different in Chakra

**Comment by nbouvrette** [comment]
I've made a few tests this weekend and it looks like as soon as I add `_app.js` with the following code, the inline CSS seems to appear right away:

```ts
import { ChakraProvider } from '@chakra-ui/react';

function MyApp({ Component, pageProps }) {
  return (
    <ChakraProvider>
      <Component {...pageProps} />
    </ChakraProvider>
  );
}

export default MyApp;
```

This seems a bit different than the implementation in `npx create-next-app --example with-emotion-vanilla with-emotion-vanilla-app` - should I try to open an issue with Emotion to see if this is expected?

**Comment by kerbe** [comment]
I found this issue as I try to get my NextJS project with Chakra UI to validate. I have basicly currently just followed NextJS initialization, then followed Chakra UI documentation "Getting Started with NextJS". My `_app.js` is same as nbouvrette showed in comment above (same that comes from Chakra documentation). I don't have `_document.js` in my project.

Validation is tried after I have done `next build && next export` and then used `surge.sh` to deploy this test.

I'd expect that at this point, basic "Hello world!" index would be valid, as I have followed documentation this far. 

https://github.com/chakra-ui/chakra-ui-docs/issues/644#issuecomment-1146753917 comment from @segunadebayo though sounds that current behavior is correct and acceptable... If that's the case, I'd like to hear some reference where it is stated that invalid html code is fine to output, and that it doesn't have any bad side effects to SEO or usability of the site.

**Comment by nbouvrette** [comment]
@kerbe I don't know if you looked at the links I provided, (for example this one from the [W3C validator](https://github.com/validator/validator/issues/489)), but `<style>` tags inside the`<body>` does not follow HTML specifications.

This means that it could (or could not) have any side-effect.. it really depends on how people followed the specifications. And if it doesn't have any impact today it doesn't mean it won't have any tomorrow.

Knowing all this, and also that there are ways to make this work with Emotion (see `npx create-next-app --example with-emotion-vanilla with-emotion-vanilla-app`),  I still don't understand how we cannot reproduce the same behavior with Chakra. I'm not a Chakra or Emotion expert so I only did a basic investigation but if you have more knowledge than me on the topic, I would like to understand why this is happening.

**Comment by naman-ali** [comment]
This problem also makes Chakra to not support AMP, as it gives the following error:
`The parent tag of tag 'style amp-custom' is 'section', but it can only be 'head'`

There are other issues when using Chakra with AMP like:
`Custom JavaScript is not allowed.`

**Comment by nbouvrette** [comment]
@nikolovlazar @segunadebayo @TylerAPfledderer any update on this issue? Just got a notification that it's about to be auto-archived.

**Comment by nbouvrette** [comment]
Still no news on this one?

**Comment by nikolovlazar** [comment]
After looking at this with @segunadebayo we found that using `@emotion/styled` (which is what we use under the hood) results in placing the `<style>` tags right next to the component. There is a way to fix this issue and put all of the styles in the `<head>`, but that includes overriding Next.js's server and opting out of all of the Next.js Optimizations.

Overriding the Next.js Server: https://nextjs.org/docs/advanced-features/custom-server
A reproduction repo that we made: https://github.com/nikolovlazar/emotion-vanilla-ssr

I'm closing this issue because there's nothing to do at this moment. Sorry.

**Comment by nbouvrette** [comment]
Thanks @nikolovlazar and @segunadebayo.

I am sure what you did exactly on your [reproduction repo](https://github.com/nikolovlazar/emotion-vanilla-ssr)? it looks like you simply cloned `npx create-next-app --example with-emotion-vanilla with-emotion-vanilla-app` - I don't see any custom-server code on there and of course, this wouldn't be a viable solution.

Regarding your comment about `@emotion/styled`, I was finally able to reproduce the issue. Basically, as soon as I use `@emotion/styled`, the CSS is left inline: https://github.com/nbouvrette/emotion-inline-css-issue

But what I am still confused about is that Chakra uses `@emotion/css` and not `@emotion/styled`? Can you share more details on how to reproduce this issue using `@emotion/css` because if Chakra does not use `@emotion/styled`, then it surely isn't the cause of the issue in this thread and I am unable to continue the investigation with Emotion.

I think it might be good to leave this issue open in the meantime until we understand what is going on?

**Comment by nbouvrette** [comment]
@nikolovlazar @segunadebayo @TylerAPfledderer any update on my last comment? I'm just looking for a clear explanation of what is causing this so that I can propose ideas... right now it's unclear still and the issue is closed again :(

**Comment by Fritze1602** [comment]
It would be amazing, if there would be a way to fix the errors and provide valid HTML only to prevent Irritations in using the wonderful Chakra UI in combination with next.js. Although @segunadebayo was so kind to explain the reasons, for some people (customers) this might be a reason for a NoGo  decision for using your amazing library. Or even worse a warning of a defect with legal implications. I feel this is of high interst for many reasons.

**Comment by nbouvrette** [comment]
@Fritze1602 I don't believe the answer that was provided to us so far is accurate. I am still unable to explain why Chakra is having this issue based on my last few comments. 

@nikolovlazar @segunadebayo @TylerAPfledderer is there any chance you might re-open this issue to provide further information?

**Comment by semihkaragozoglu** [comment]
is there a way to fix this issue?
i have strange CLS problem on my ssg web site especially in crossbrowser (some mobile browsers)
im suspecting this could cause the problem
@nikolovlazar do you have any idea how to put style tags with Next custom server
