### ISSUE TITLE
Vercel incorrectly referenced as ZEIT in example docs

### ISSUE THREAD

**Issue by Mayur57** [chakra-ui/chakra-ui-docs#652]
### Subject

Example

### Description

The docs reference Vercel organisation with its previous name, ZEIT. This should be updated.

**Comment by nikolovlazar** [comment]
@Mayur57 where exactly is this?

**Comment by Mayur57** [comment]
The README for Next.js example in the main repository here: https://github.com/chakra-ui/chakra-ui/tree/main/examples/next-js

I think its a mistake that the issue was opened here. I meant to post an issue in the main repository but the **Documentation** option opened it here. Closing this issue for the same. If this is the intended, please re-open the issue.

I have posted a pull request for the same as [PR#6108](https://github.com/chakra-ui/chakra-ui/pull/6108).
