### ISSUE TITLE
Create CodeSandbox examples for Responsive Variants / Sizes

### ISSUE THREAD

**Issue by nikolovlazar** [chakra-ui/chakra-ui-docs#656]
### Description

Create CodeSandbox examples for Responsive Variants / Sizes, plus add some use cases for them.

@aacevski can also make a couple of Chakra UI Shorts videos using those examples.

**Comment by m4x3d** [comment]
Hey,
as I wrote documentation for this feature I tried a few things out and created also a kind of a playground/template. As I am not that creative for finding good use cases I can at least provide my sandboxes:

- template: https://codesandbox.io/s/responsive-variants-playground-66hhkc
- sizes **vs** responsive variants **vs** overwrite in the component (possibly all cases for a single part component in one file, kind of a mess :D) https://codesandbox.io/s/responsive-variants-playground-forked-y43472
