### ISSUE TITLE
How is "If you use the `size` prop, the font size of the heading will automatically decrease in size for smaller screens." true?

### ISSUE THREAD

**Issue by advename** [chakra-ui/chakra-ui-docs#667]
### Description

While reading through the documentation, I noticed that the [`<Text>` component examples uses `fontSize`](https://github.com/chakra-ui/chakra-ui-docs/blob/main/pages/docs/components/typography/text.mdx#changing-the-font-size) as props, while [`<Heading>` examples uses `size`](https://github.com/chakra-ui/chakra-ui-docs/blob/main/pages/docs/components/typography/heading.mdx#changing-font-size). 

The documentation explains this with
> To increase the size of the heading, you can use the fontSize or size props. **If you use the size prop, the font size of the heading will automatically decrease in size for smaller screens.**

However, how is this true if both `size` and `fontSize` props use rem as sizes?
- https://github.com/chakra-ui/chakra-ui/blob/main/packages/theme/src/foundations/sizes.ts
- https://github.com/chakra-ui/chakra-ui/blob/main/packages/theme/src/foundations/typography.ts#L47

Shouldn't the `size` prop then use an [array of values](https://chakra-ui.com/docs/styled-system/features/responsive-styles#the-array-syntax)?

Or why even have the inconsistency of size and fontSize. Stay true to the native attribute `fontSize` like you also mention [here in the documentation](https://chakra-ui.com/docs/styled-system/theming/theme#typography).

**Comment by m4x3d** [comment]
Hey,
it is true regarding the `sizes` of `Heading` in the [theme source](https://github.com/chakra-ui/chakra-ui/blob/main/packages/theme/src/components/heading.ts) (you can find a direct link at top of every component page which is themed) which are used with the `size` prop. Internally the size has an array of values for the fontSizes, at least at fontSize `lg` and above.

Since the last point is not well documentated I will create a PR for this. :)

**Comment by advename** [comment]
Alright - now i can see the difference. However, even if this is documented, it may lead to confusion for the devs like me who looked at the source code for sizes and not inside the heading component.

I would therefore suggest to either:
- Use a more distinctive prop name, available only to Heading, to specify these dynamic sizes
- Use fontSize, and add the list of dynamic sizes to typography with distinctive names, e.g.
```js
const theme = extendTheme({
 ...
  fontSizes: {
    xs: "0.75rem",
    sm: "0.875rem",
    md: "1rem",
    lg: "1.125rem",
    xl: "1.25rem",
    "2xl": "1.5rem",
    "3xl": "1.875rem",
    "4xl": "2.25rem",
    "5xl": "3rem",
    "6xl": "3.75rem",
    "7xl": "4.5rem",
    "8xl": "6rem",
    "9xl": "8rem",
    
    // Distinctive dynamic fontSizes
      "h-4xl": {
          fontSize: ["6xl", null, "7xl"],
          lineHeight: 1,
        },
        "h-3xl": {
          fontSize: ["5xl", null, "6xl"],
          lineHeight: 1,
        },
        "h-2xl": {
          fontSize: ["4xl", null, "5xl"],
          lineHeight: [1.2, null, 1],
        },
        "h-xl": {
          fontSize: ["3xl", null, "4xl"],
          lineHeight: [1.33, null, 1.2],
        },
        "h-lg": {
          fontSize: ["2xl", null, "3xl"],
          lineHeight: [1.33, null, 1.2],
        },
        },
  ...
}
```
(Ofc this `h-XX` is just a suggestion, but you get the idea).

The reason behind this is that having multiple source of truths is an anti-pattern in UI libraries. There are too many size values hidden away. A user should have a straightforward and distinctive overview of what belongs to what. Having different `size` values for different components is a big pain-point.

**Comment by m4x3d** [comment]
I know what you mean, but I do not think it is a problem. Yes, there is a conflict in the naming, but the `sizes` from the top level of the theme are in my opinion adequately documented on the [Default Theme page](https://chakra-ui.com/docs/styled-system/theming/theme#sizes) and just for having global values for `width`, `height` and so on.

The `size` prop of each component is more or less a set of predefined styles which also includes the `fontSize` in most cases, e.g. the [Checkbox](https://chakra-ui.com/docs/components/form/checkbox#checkbox-sizes) component.

**Comment by advename** [comment]
> adequately documented on the [Default Theme page](https://chakra-ui.com/docs/styled-system/theming/theme#sizes) and

I dare to disagree. Using a User story:
**As a** UI library user, 
**I want** to see the Heading sizes values, beside other components sizes values,
**So that** i know which sizes values are applied to my component.

However, currently, the "adequately documented" size values only show:
```js
mport { extendTheme } from '@chakra-ui/react'

const sizes = {
  sizes: {
    ...theme.space,
    max: 'max-content',
    min: 'min-content',
    full: '100%',
    '3xs': '14rem',
    '2xs': '16rem',
    xs: '20rem',
    sm: '24rem',
    md: '28rem',
    lg: '32rem',
    xl: '36rem',
    '2xl': '42rem',
    '3xl': '48rem',
    '4xl': '56rem',
    '5xl': '64rem',
    '6xl': '72rem',
    '7xl': '80rem',
    '8xl': '90rem',
    container: {
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
    },
  },
}

const theme = extendTheme({ sizes, ...})
```

Reading through this - my first understanding is that when i use `<Heading size="xl" />`, that my heading font receives `font-size: 36rem`.

If you want to use size props, that works differently accross multiple components, then this should be documented and mentioned in more detail. As for now, the default theme page is the only place within the docs that explains a bit about size - which gives the user an understanding that these are the values that are applied to everything whenever i use `size` - aka, the only source of truth.

**Comment by nikolovlazar** [comment]
@advename the sizes section in the theme has nothing to do with the Heading sizes. Just as you would do `<Button size='sm'>`, the Heading component has its own sizes defined [here](https://github.com/chakra-ui/chakra-ui/blob/main/packages/theme/src/components/heading.ts#L8). The sizes section in the theme you're referring to is used for widths, heights, etc...

**Comment by advename** [comment]
@nikolovlazar I understood that - but what i meant is that a user doesn't know that. You maybe do since you've been working on/with it for some time - but as someone who starts out using the library, I would not have expected to start looking into the source code to find out the default values. If this is not documented, then the user simply believes that the `size` value on the theme customization page are true for everything.

I.e., I would suggest that these default values are mentioned on the <Heading> component page, so that the user gets a feeling that `size` values are different for different components.

**Comment by nikolovlazar** [comment]
@m4x3d added a simple sentence that lets the user know where they can check the sizes values. That should do it for now. We do plan a docsite redesign, which will make the usage, learning, and feature discovery easier, so we'll take this into consideration.

**Comment by advename** [comment]
Can we at least then link to the file in the docs? To ease the access, but aswell highlight the point?
```
To increase the size of the heading, you can use the `fontSize` or `size` props.
If you use the `size` prop, the font size of the heading will automatically
decrease in size for smaller screens, but only by using size `lg` or above with
the default theme. This can be seen in the [theme source](https://github.com/chakra-ui/chakra-ui/blob/main/packages/theme/src/components/heading.ts) for the component.
```

**Comment by nikolovlazar** [comment]
Yeah, that would be a good idea as well! You wanna do that?

**Comment by advename** [comment]
Could you do that? I still have an open MR https://github.com/chakra-ui/chakra-ui-docs/pull/657 and am busy with a project :)
