### ISSUE TITLE
Wrong documentation for Link

### ISSUE THREAD

**Issue by waptik** [chakra-ui/chakra-ui-docs#68]
### Description

When i visit https://chakra-ui.com/docs/navigation/link, documentation about `Link` should show but right now, it is the documentation for `LinkOverlay` that's being shown.
![image](https://user-images.githubusercontent.com/1687551/143778879-b6333447-b508-4a57-a2d4-728d52472e6a.png)

**Comment by lazarnikolov94** [comment]
Thanks for noticing this @waptik! I've opened a PR with the fix: https://github.com/chakra-ui/chakra-ui-docs/pull/79
