### ISSUE TITLE
Skeleton `fadeDuration` clarification needed

### ISSUE THREAD

**Issue by Philzen** [chakra-ui/chakra-ui-docs#685]
### Subject

Skeleton

### Description

It's not obvious what the `fadeDuration` prop does from reading the docs. I was strongly assuming/hoping one could influence the fadeIn/fadeOut speed in between cycles.

The prop documentation could be more specific here, something like "The fadeIn duration of the content in seconds, once `isLoaded` becomes true`".

@itkrt2y also provided a nice codesandbox example over at https://github.com/chakra-ui/chakra-ui/issues/6126 – having may also be nice to be included in the docs to illustrate the functionality.

**Comment by TylerAPfledderer** [comment]
Hey @Philzen! Nice catch. 👍🏼 

Indeed, this renders the duration value in the `animation` prop supplied to the component, and the property is rendered when `isLoaded` is true. [Lines 97 - 109 in the source code](https://github.com/chakra-ui/chakra-ui/blob/main/packages/skeleton/src/skeleton.tsx#L97-L109)

I can certainly work on that unless you want to pull a PR. 😄

**Comment by TylerAPfledderer** [comment]
@nikolovlazar you can go ahead and assign me on this one, along with providing any additional input you may have. Would need to pull a PR in the package to update the prop table as well as providing clear documentation on how `fadeDuration` is used with `isLoaded`.
