### ISSUE TITLE
Update props table below components for better readability

### ISSUE THREAD

**Issue by mannycarrera4** [chakra-ui/chakra-ui-docs#709]
### Subject

Text

### Description

I was trying to read through the props table and it's slightly confusing. There's technically nothing wrong, but i think it can be slightly improved! If you look at the image below, it looks like the documentation for `colorScheme` belongs to that section between the two borders, however, the documentation is actually before that section after the border. Is it possible to group the `prop` and description between the two borders for more clarity?

Thanks again! Love all the work you all have put in!

<img width="871" alt="Screen Shot 2022-06-09 at 12 44 01 PM" src="https://user-images.githubusercontent.com/7966550/172921794-fd709cd6-ce79-4fff-8d5b-dfa5266b064e.png">

**Comment by TylerAPfledderer** [comment]
@nikolovlazar I have three quick solutions:

1. Move the border
![image](https://user-images.githubusercontent.com/65234762/173128169-d1962c21-18a9-4aaf-8640-837770691b9e.png)

2. Add more spacing between props (subtle change)
![image](https://user-images.githubusercontent.com/65234762/173128906-330ef3f0-c215-4ada-b27f-4957908d8109.png)

3. Reduce spacing between the prop name and the border, and add spacing between props.
![image](https://user-images.githubusercontent.com/65234762/173129357-c06cf146-efbe-4164-8ded-023318eae169.png)

**Comment by nikolovlazar** [comment]
@TylerAPfledderer that looks about right!

**Comment by TylerAPfledderer** [comment]
@nikolovlazar ok! So which one? 😁

**Comment by nikolovlazar** [comment]
@TylerAPfledderer last one 😅
