### ISSUE TITLE
(i18n): Request to add Japanese Documentation

### ISSUE THREAD

**Issue by wattanx** [chakra-ui/chakra-ui-docs#71]
### Subject

Request to add Japanese Documentation

### Description

First of all, thank you chakra-ui community for this awesome library! 

I've just started usnig chakra and I think its wonderful!
But, It's hard for some Japanese developers to read English documentation.
Therefore, I would like to add Japanese documentation.

I can help with the Japanese translation if need be.

Thank you.

**Comment by nikolovlazar** [comment]
Closing translation issues for now. See https://github.com/chakra-ui/chakra-ui-docs/issues/86#issuecomment-983356376.
