### ISSUE TITLE
(docs): create a hooks page for the Checkbox hooks

### ISSUE THREAD

**Issue by antoninu** [chakra-ui/chakra-ui-docs#72]
In the Checkbox documentation there is a section about hooks. This one only mentions `useCheckbox` and `useCheckboxGroup` but does not give any information on how they should be used or an example.

Here is a link to the section: https://chakra-ui.com/docs/form/checkbox#hooks

They should include the return values, parameters, and at least one usage case as an example.

> Moderator note: we should create a new page for the checkbox hooks in the "Hooks" section, but reference it in the Checkbox component page.

**Comment by lazarnikolov94** [comment]
I agree @anubra266. We should put the hooks docs into their own page in the Hooks section, but we can reference that page from the Checkbox page.

**Comment by noobinthisgame** [comment]
@lazarnikolov94 I'd like to a shot on this one. If you could assign me that would be great <3
