### ISSUE TITLE
Updating getting started guides to use yarn command that works with newer yarn versions

### ISSUE THREAD

**Issue by caelinsutch** [chakra-ui/chakra-ui-docs#729]
### Subject

GettingStarted

### Description

Currently, the documented command for installing modules via yarn is:

```
yarn add @chakra-ui/react @emotion/react@^11 @emotion/styled@^11 framer-motion@^6 @emotion/server@^11
```

However, in newer versions of yarn, this will cause the error 

```
no matches found: @emotion/react@^11
```

This command should be:

```
yarn add @chakra-ui/react "@emotion/react@^11" "@emotion/styled@^11" "framer-motion@^6" "@emotion/server@^11"
```

**Comment by nikolovlazar** [comment]
@caelinsutch thanks for raising this issue. What version of `yarn` are you using?

**Comment by caelinsutch** [comment]
@nikolovlazar do you want a PR to update the docs? This is pretty low impact though haha.

**Comment by nikolovlazar** [comment]
We're working on a major docsite refactor that will solve this issue. I'm closing this for the time being.
