### ISSUE TITLE
Outdated `Chakra UI + Capsize` doc guide

### ISSUE THREAD

**Issue by TylerAPfledderer** [chakra-ui/chakra-ui-docs#733]
### Subject

Chakra Capsize

### Description

The [@ceteio/chakra-capsize](https://github.com/ceteio/chakra-capsize) package has not seen an update in the last 9 months, and therefore is not compatible with React 18 (ran into dependency errors when initially attempting to download it).

At the moment, I suggest removing the page regarding use of this package from the v2 docsite as it will simply be unusable.

**Comment by noobinthisgame** [comment]
I think before removing it we should and a warning above it that it is only compatible with chakra < v2
