### ISSUE TITLE
(docs): Add extensions/packages section to Community Resources page

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-ui-docs#74]
We have a number of community-created extensions and packages that I think we should reference in the docs. An example of this is @jeanverster's [`chakra-ui-steps` package](https://github.com/jeanverster/chakra-ui-steps).

**Comment by YenTingWu** [comment]
I think community-created extensions and packages belong to a part of the `libraries` category. Maybe we can put them under it. What do you guys think?

**Comment by YenTingWu** [comment]
@nikolovlazar I think `extensions/package` has the same concept with `libraries`, what do you think? 

If they have the same concept, maybe we can add [chakra-ui-steps](https://github.com/jeanverster/chakra-ui-steps) into `awesome-chakra-ui` and close this issue.

**Comment by nikolovlazar** [comment]
@YenTingWu definitely. All of those fall under the same umbrella `libraries`.

**Comment by nikolovlazar** [comment]
@YenTingWu definitely. All of those fall under the same umbrella `libraries`. Btw `chakra-ui-steps` have already been added in the awesome repo, so I'm closing this issue.
