### ISSUE TITLE
Small typos in "Guide to creating Components" page

### ISSUE THREAD

**Issue by givensuman** [chakra-ui/chakra-ui-docs#741]
### Description

Page: https://chakra-ui.com/guides/advanced/component-guide
Route: Advanced > Component Guide

Towards the bottom of the page, there are a few listed resources reading:

```
Resources
- Aria Practices: https://www.w3.org/TR/wai-aria-practices/
- Lightning Design System: https://www.lightningdesignsystem.com/

TypeScript
- Clean Code Guide: https://github.com/labs42io/clean-code-typescript
- Best TypeScript Practices:https://github.com/typescript-cheatsheets/react-typescript-cheatsheet
```

There's a missing leading space before the "Best TypeScript Practices" link, and the "Aria Practices" link is no longer an active document on w3.org.

To fix, add the leading space and change the "Aria Practices" link to `https://www.w3.org/TR/wai-aria-practices/`.

**Comment by TylerAPfledderer** [comment]
Closing this issue due to [this PR comment](https://github.com/chakra-ui/chakra-ui-docs/pull/742#issuecomment-1164022143)
