### ISSUE TITLE
Fix docsite redirects

### ISSUE THREAD

**Issue by nikolovlazar** [chakra-ui/chakra-ui-docs#747]
### Description

When we restructured the docsite some of the old links do 404. Add the proper redirects to support the old shared links throughout the internet.

Related: #746

**Comment by nikolovlazar** [comment]
I'm reopening this issue since there are still some redirects missing.

**Comment by noobinthisgame** [comment]
Seems like we still have some links missing https://github.com/chakra-ui/chakra-ui-docs/pull/759

**Comment by JulienLemaitre** [comment]
Hi,

I've pushed a redirect for broken `/styled-system/features/` segment in path, and fixed the related internal links in docs : https://github.com/chakra-ui/chakra-ui-docs/pull/768
