### ISSUE TITLE
Add more documentation of each Components theme object

### ISSUE THREAD

**Issue by Patrick-Ullrich** [chakra-ui/chakra-ui-docs#75]
### Subject

All Components

### Description

Whenever you want to style a component, you most likely end up going to the `View theme source` button of each component. This often then leads you to the @chakra-ui/anatomy folder, to investigate all parts. The `View theme source` has been a welcome addition a while back, but I don't think it's the most user friendly, especially for new comers.

I am wondering if we could create a more user friendly documentation around the theme file. 

Taking Input component as an example, we could add another section at the end of the documentation (https://chakra-ui.com/docs/form/input)

### Theme
List of parts: field, addon
<insert some graphic pointing out which part is which?>

I am not sure how far one has to go, but potentially more information about inheritance as well? E.g. textarea takes from input by default, or the relationship between button and Icon button.

Would love to gage the interest in this, and more than willing to take a crack at it.

**Comment by YenTingWu** [comment]
I'd like to do this one as well!

**Comment by nikolovlazar** [comment]
Getting solved by #1100
