### ISSUE TITLE
Starter code on Getting Started page causes infinite loop

### ISSUE THREAD

**Issue by lachieh** [chakra-ui/chakra-ui-docs#751]
## Description
The following section of the Getting Started page will cause an infinite loop if used directly. The App function definition will be called recursively. While this is pretty easy to identify for most experienced developers, some of my students had issues with this.

https://github.com/chakra-ui/chakra-ui-docs/blob/fada8f3ef350a488edb205ebcfd99e42a0c4bf38/content/getting-started/index.mdx#L27-L34

## Resolution
There are few ways to resolve this, so I wanted to discuss before submitting a PR. The way I see it, we can either update the name of the function definition, or use a fake component inside the `ChakraProvider` to indicate a typical app container.

Another solution would be to mimic what a typical `index.js` file might look like instead of `App.js`, though the change from React 17 to 18 changed a few things relating to the root element, so a little more hesitant to suggest that. Maybe I'm over thinking and most people will be on v18 when adding Chakra for the first time anyway.

**Comment by noobinthisgame** [comment]
Hey @lachieh thanks for reporting this! I'd go with the fake component name in the `ChakraProvider`

**Comment by lachieh** [comment]
Thanks @noobinthisgame, PR created 👌🏻
