### ISSUE TITLE
Website sidebar scrolls to some other position after selection.

### ISSUE THREAD

**Issue by gnasamx** [chakra-ui/chakra-ui-docs#77]
# Bug report

## Describe the bug
Sidebar scrolls to some other position after clicking on different list group item. But it does not scroll if same group item is selected.

## To reproduce

1. Scroll sidebar down to very bottom.
2. Click on 'useBreakpointValue'.
3. Click on 'Avatar'.
4. Sidebar will scroll to some another position.

## Expected behavior
Selected sidebar list item should not scroll to some other position. Item should stay below mouse cursor.

## Screenshots

![ezgif com-resize](https://user-images.githubusercontent.com/46209368/99097536-c4953b00-25fd-11eb-8316-910962c37c8d.gif)

## System information

- OS: macOS
- Browser (if applies): Safari 13.1.1

**Comment by noobinthisgame** [comment]
I tried to reproduce this on the latest chrome, safari and firefox and it seems to be resolved.

**Comment by lazarnikolov94** [comment]
Closing this because the issue has been resolved.
