### ISSUE TITLE
Popover Placements props link is not working

### ISSUE THREAD

**Issue by ValGeorgiev** [chakra-ui/chakra-ui-docs#773]
### Subject

Popover placements

### Description

I am trying to see all of the possible values that we can pass on Popover placement props. 

```
Since popover is powered by PopperJS, you can change the placement of the popover by passing the placement prop. See the [props](https://chakra-ui.com/docs/components/popover/usage#props) for the possible placement values.
```
The props link is not working, I think the anchor tag is missing on the page.

**Comment by TylerAPfledderer** [comment]
Thank you for catching this, @ValGeorgiev! Looks like this link was missed when we transitioned to a new navigation structure.

It is supposed to navigate to the new [props tab](https://chakra-ui.com/docs/components/popover/props).

Though upon further review, I believe it should've originally linked to the PopperJS documentation itself, specifically the `createPopper` [Options](https://popper.js.org/docs/v2/constructors/#options) which properly lists all the values you can use in the `placement` prop. Just looking at the `placement` prop on the props page does not provide us a list of options.

@noobinthisgame or @nikolovlazar, do you think we should be providing an external link to Popper or should we look to provide the list somewhere on the page? Maybe something like this:
![image](https://user-images.githubusercontent.com/65234762/176578218-f6182076-4c74-4ad5-8d71-ac0f16239370.png)
