### ISSUE TITLE
(docs): `SliderMark` not mentioned in the doc, and `SliderThumb` with tooltip 

### ISSUE THREAD

**Issue by stla** [chakra-ui/chakra-ui-docs#78]
Hello,

  The `SliderMark` tag is not mentioned in the [online documentation](https://chakra-ui.com/). [Here](https://codesandbox.io/s/test-5lcco?file=/src/App.js) is an example.

  That said, I find it's easier to set a tooltip to the `SliderThumb`.

```jsx
  const [sliderValue, setSliderValue] = React.useState(5);
  <Slider id="slider" defaultValue={5} min={0} max={10} colorScheme="blue" onChange=(v) => {setSliderValue(v)}>
    <SliderTrack>
      <SliderFilledTrack />
    </SliderTrack>
    <Tooltip hasArrow bg="red.600" placement="top" closeOnClick={false} isOpen label={sliderValue}>
      <SliderThumb />
    </Tooltip>
  </Slider>
```

**Comment by lazarnikolov94** [comment]
There's been a PR on the main repo for this: https://github.com/chakra-ui/chakra-ui/pull/4771. The code needs to be cleaned up (should use design tokens, not pixel values), so anyone who wants to work on this can use this PR as a reference.

**Comment by lazarnikolov94** [comment]
@stla would you like to take a swing at this?

**Comment by YenTingWu** [comment]
I'll take this issue

**Comment by stla** [comment]
By the way there is also `RangeSliderMark` now. But well, it's not necessary to provide an example once an example of `SliderMark` is given.

Cheers.
