### ISSUE TITLE
use sandpack everywhere

### ISSUE THREAD

**Issue by segunadebayo** [chakra-ui/chakra-ui-docs#790]
### Subject

react-live => sandpack

### Description

I'd like for us to use the same package for code editing everywhere in the docs. The beta version of the React docs showcases the power of Sandpack (https://beta.reactjs.org/learn).

We need to leverage this in our docs as well.

**Comment by TylerAPfledderer** [comment]
@segunadebayo I'll get a draft PR up, but here is a working solution.

## Closed:
![image](https://user-images.githubusercontent.com/65234762/176825470-126815e0-12a7-4583-9a96-1ae9cdd499e3.png)

## Open
![image](https://user-images.githubusercontent.com/65234762/176825524-15ecb733-b142-40ef-ac21-74a26bffde32.png)

**Comment by TylerAPfledderer** [comment]
Unless I can find something dynamic to extract component names from the markdown codeblock string (unlikely and very challenging), the component imports still have to be declared in the codeblock like in the existing examples that use the sandpack embed.

**Comment by nikolovlazar** [comment]
We've decided to stick with `react-live` for the simpler examples and sandpack for the more complex examples.
