### ISSUE TITLE
Docs are misleading, a `theme` is required to get the default styles

### ISSUE THREAD

**Issue by RebootGG** [chakra-ui/chakra-ui-docs#797]
### Subject

Installation / Getting Started

### Description

With a Next.js (12.2.0) project, the minimal setup to use the default styles, as per the docs, is : 

1. _run the command_ `yarn add @chakra-ui/react @emotion/react@^11 @emotion/styled@^11 framer-motion@^6`
2. _Go to pages/_app.js or pages/_app.tsx (create it if it doesn't exist) and wrap the Component with the ChakraProvider:_

With these 2 steps, the basic default styles are not imported and the components are unstyled, eg here is the appearance of a `<Button>` :

![image](https://user-images.githubusercontent.com/29600338/176890119-b788b741-a4fe-49a3-83b2-30e83dcbe5fa.png)

When it should look like this :
![image](https://user-images.githubusercontent.com/29600338/176891223-9fc13304-6296-4479-a894-e7d5d5a5b5ba.png)

The third step in the docs is actually mandatory to get the default styles, **even when you just want to use the default styles** : 

3. _If you intend to customise the default theme object to match your design requirements, you need to extend the theme. Chakra UI provides an extendTheme function that deep merges the default theme with your customizations._

To make it work, I had to add a theme to the Provider like this : 

![image](https://user-images.githubusercontent.com/29600338/176890626-449c5db6-9db8-4bef-bf4c-d44acf50c792.png)

IMO, we should either :
- specify in the docs that this last step is mandatory to import the default styles.
- make sure the default styles are imported without having to add an "empty" theme as I did.

**Comment by TylerAPfledderer** [comment]
Hey @RebootGG! 

Sorry to hear you are having trouble with this. Are you able to provide a minimal repro in CodeSandbox?

I have at least one project myself using Next, and the DocSite itself runs in Next. I also spun up a test app.  I'm unfortunately not able to reproduce this issue. 🤔

**Comment by nikolovlazar** [comment]
I can't reproduce this issue. Not sure if it's an issue on @RebootGG's end, or an issue in an older version of Chakra UI / Next.js. Here's a codesandbox link that proves that you don't need the `theme` prop to have the default styles: https://codesandbox.io/s/zealous-cookies-xgiimu?file=/pages/index.tsx.
