### ISSUE TITLE
Invalid prop used in Flex component

### ISSUE THREAD

**Issue by s7m4b4** [chakra-ui/chakra-ui-docs#853]
### Subject

Style Props

### Description

I noticed that the Flex elements in the Filters and BackdropFilters examples [here](https://chakra-ui.com/docs/styled-system/style-props#filter=) are using an invalid prop - `spacing`. This is a bit misleading and redundant as `gap` already exists on the component.

It's not a huge deal but blindly copying it into a TSX template and you'll be greeted with this type error which threw me for a minute -
`(property) spacing: string
Type '{ children: string; spacing: string; }' is not assignable to type 'IntrinsicAttributes & OmitCommonProps<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, keyof FlexProps> & FlexProps & { ...; }'.
  Property 'spacing' does not exist on type 'IntrinsicAttributes & OmitCommonProps<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, keyof FlexProps> & FlexProps & { ...; }'.ts(2322)`

**Comment by TylerAPfledderer** [comment]
Hey @s7m4b4. Great catch! Thank you for opening this issue. I'll look to have this addressed, unless you would like to open a PR to make this correction! 😄
