### ISSUE TITLE
Form Control theme link incorrect

### ISSUE THREAD

**Issue by Patrick-Ullrich** [chakra-ui/chakra-ui-docs#862]
### Description

When clicking on `Theme Source`, I get an invalid link for <FormControl.

1. Go to https://chakra-ui.com/docs/components/form-control
2. Click `Theme Source`

Goes to:
https://github.com/chakra-ui/chakra-ui/tree/main/packages/theme/src/components/form-control.ts

But should go to:
https://github.com/chakra-ui/chakra-ui/blob/main/packages/theme/src/components/form.ts

I haven't looked yet, but I assume this is because form-control breaks the convention slightly.  (form instead of form-control) e.g. FormError source code is also kind of related to this component, but there isn't a theme source link at all. 

For completion:
- Form Error: https://github.com/chakra-ui/chakra-ui/blob/main/packages/theme/src/components/form-error.ts
- Form Label: https://github.com/chakra-ui/chakra-ui/blob/main/packages/theme/src/components/form-label.ts

**Comment by TylerAPfledderer** [comment]
Hey @Patrick-Ullrich! Nice catch. This looks to be in how the frontmatter is being used in the form-control [usage.mdx](https://github.com/chakra-ui/chakra-ui-docs/blob/main/content/docs/components/form-control/usage.mdx?plain=1#L2). The `id` is being passed as a prop to generate the list of component links. 

Per `FormControl` this might be an edge case due to there being multiple theme files related to this multi-component.

**Comment by TylerAPfledderer** [comment]
Hey @Patrick-Ullrich! Nice catch. This is coming from the generated frontmatter of each doc page, where the `package` value is parsed in the [component layout](https://github.com/chakra-ui/chakra-ui-docs/blob/main/layouts/component.tsx#L16). As a short-term temporary solution, It looks like when passing this value as `id` to the `theme` prop of `ComponentLinks` in line 30, we could add to the check for `form-control`

```jsx
<MDXComponents.ComponentLinks
  theme={!['layout', 'form-control'].includes(id) && { componentName: id }}
  github={{ package: id }}
  npm={{ package: frontmatter.package }}
/>
```

I currently can not identify a more long-term solution for this case with how `ComponentLinks` is created.

**Comment by nikolovlazar** [comment]
Already fixed. Closing this issue.
