### ISSUE TITLE
Add documentation for project outside react or javascript

### ISSUE THREAD

**Issue by Rizary** [chakra-ui/chakra-ui-docs#863]
### Subject

using chakra-ui outside typescript/react project

### Description

So I have upcoming project using rust's webassembly. I found that compiling chakra-ui using rollup really uncomfortable, so I might asking if it is possible to add the documentation on how to use chakra-ui? There is some request to add it into cdn like in here: https://github.com/chakra-ui/chakra-ui/issues/341 so I can just include in my index.html

This is some example on my wasm project: https://github.com/Rizary/dominator-site

**Comment by nikolovlazar** [comment]
We haven't done any testing on Chakra UI in Web Assembly, and it's not a priority right now, so I'm closing this issue.
