### ISSUE TITLE
Codesandbox on V1 docs home page is broken

### ISSUE THREAD

**Issue by IanVS** [chakra-ui/chakra-ui-docs#896]
### Description

I'm exploring the use of Chakra in my app, and noticed that there is an error on https://v1.chakra-ui.com/ in a codesandbox 

### Link to Reproduction

https://v1.chakra-ui.com/

### Steps to reproduce

Go to https://v1.chakra-ui.com/, scroll down, see this:

<img width="1426" alt="image" src="https://user-images.githubusercontent.com/4616705/178840840-efb2dc7d-35c4-4262-9dca-f4912a99d509.png">

### Chakra UI Version

1.8.8

### Browser

Brave v1.40.113

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by nikolovlazar** [comment]
Good catch, @m4x3d!
