### ISSUE TITLE
Shootproof page not found 

### ISSUE THREAD

**Issue by aroyan** [chakra-ui/chakra-ui-docs#900]
### Description

In the supported and backed section on the index page, shootproof page is not found. I think this needs to be updated.
![broken link in index](https://user-images.githubusercontent.com/43630681/183242270-f9c805e8-42d9-4232-9af7-8f53cd72c4cc.gif)

**Comment by TylerAPfledderer** [comment]
@aroyan Great callout! The link currently points to `https://www.shootproof.com/hp` when it should just be `https://www.shootproof.com`

**Comment by aroyan** [comment]
> @aroyan Great callout! The link currently points to `https://www.shootproof.com/hp` when it should just be `https://www.shootproof.com`. You can definitely roll out a PR for this. :)

fixed it on #902
