### ISSUE TITLE
`StyleFunctionProps` is not exported by `@chakra-ui/theme-tools`

### ISSUE THREAD

**Issue by RunDevelopment** [chakra-ui/chakra-ui-docs#907]
### Description

[This part of the docs](https://chakra-ui.com/docs/styled-system/customize-theme#customizing-single-components) includes this code snippet.

```ts
// theme.ts (tsx file with usage of StyleFunctions, see 4.)
import { extendTheme } from '@chakra-ui/react'
import { StyleFunctionProps } from '@chakra-ui/theme-tools'
```

Copying this code with `@chakra-ui/theme-tools` version 2.0.7 installed yields the following TS error:

``` 
src/renderer/theme.ts:2:10 - error TS2459: Module '"@chakra-ui/theme-tools"' declares 'StyleFunctionProps' locally, but it is not exported.

2 import { StyleFunctionProps } from '@chakra-ui/theme-tools'
           ~~~~~~~~~~~~~~~~~~

  node_modules/@chakra-ui/theme-tools/dist/index.d.ts:3:10
    3 import { StyleFunctionProps, SystemStyleInterpolation, SystemStyleObject } from '@chakra-ui/styled-system';
               ~~~~~~~~~~~~~~~~~~
    'StyleFunctionProps' is declared here.
```

**Comment by nikolovlazar** [comment]
@RunDevelopment we've fixed this in the new `2.2.6` version. I'll close this issue for the time being, but if you still have the problem feel free to reopen the issue.

**Comment by RunDevelopment** [comment]
> new `2.2.6` version

The new version of what? 2.0.7 is the latest version of @chakra-ui/theme-tools.

**Comment by nikolovlazar** [comment]
Oh wait, it's actually wrong. The `StyleFunctionProps` come from the `styled-system` package, not the `theme-tools` (https://github.com/chakra-ui/chakra-ui/blob/main/packages/styled-system/src/component.types.ts#L30-L36).

We need to update the docs in this case. Would you like to open a PR that changes the import to `styled-system`?

**Comment by RunDevelopment** [comment]
> The `StyleFunctionProps` come from the `styled-system` package

Which version? I also looked at this package since `theme-tools` imported it from there, but `@chakra-ui/styled-system@2.1.1` doesn't even define such a type.

**Comment by RunDevelopment** [comment]
I see.

> Would you like to open a PR that changes the import to `styled-system`?

Sorry, but no. I didn't even end up using this type and just wanted to report the issue, so my commitment is rather low...

**Comment by nikolovlazar** [comment]
That's okay, @RunDevelopment. I'll push an update that fixes the instruction. Thank you for raising this issue though 🙌!
