### ISSUE TITLE
Make license type clear to new visitors: LICENSE file & github about panel

### ISSUE THREAD

**Issue by cameronelliott** [chakra-ui/chakra-ui-docs#920]
### Description

When I looked at this project's About area on the Github repo, I expected to see the license
type but it is missing.
**---START of screen shot**
<img width="327" alt="image" src="https://user-images.githubusercontent.com/868689/184961334-8659e377-e1aa-42f6-ae13-1b010c082e23.png">
**--END of screen shot**

By adding a LICENSE file this would be clear to casual visitors.
(The license is kind-of tersely expressed on the last line of the readme, and in contributing.mdx and CONTRIBUTING.md, but it's hard to find)

**I propose adding a MIT LICENSE file.**

Thank you to all contributors for this important project.

**Comment by nikolovlazar** [comment]
Good point, @cameronelliott! Thanks for raising this issue.
