### ISSUE TITLE
Broken link on Customize Theme page

### ISSUE THREAD

**Issue by knoll3** [chakra-ui/chakra-ui-docs#945]
### Description

There is a broken link on the Customize Theme page under [Customizing theme tokens](https://chakra-ui.com/docs/styled-system/customize-theme#customizing-theme-tokens).

The link for [default theme foundation style files](https://github.com/chakra-ui/chakra-ui/tree/main/packages/theme/src/foundations) returns a 404: https://github.com/chakra-ui/chakra-ui/tree/main/packages/theme/src/foundations
![image](https://user-images.githubusercontent.com/34484576/186710736-29f34ae6-c8ff-4aa2-94c6-9c74def76de0.png)

**Comment by knoll3** [comment]
Specific mdx file in question: https://github.com/chakra-ui/chakra-ui-docs/blob/main/content/docs/styled-system/customize-theme.mdx

**Comment by nikolovlazar** [comment]
@knoll3 thanks for raising this issue! I've opened a PR with the fix. 🙌
