### ISSUE TITLE
(feature): Automate monthly downloads and discord members on the homepage

### ISSUE THREAD

**Issue by noobinthisgame** [chakra-ui/chakra-ui-docs#98]
### Subject

Homepage

### Description

The discord members and monthly downloads on the homepage are still hardcoded and need to be updated manually. Would be nice if that could be automated.

**Comment by ashalfarhan** [comment]
Hi @noobinthisgame, is this issue open for anyone?

**Comment by noobinthisgame** [comment]
Hi @ashalfarhan! Yes of course :) Feel free to have a go at it :)

**Comment by ashalfarhan** [comment]
I want to work on this, but I'm figuring how can I get the discord channel members, I've searched for the Discord API Docs, and it seems like to get the channel members I need to be authenticated first, and as I'm planning is to hit npm and Discord API, is that what this should be done?
