### ISSUE TITLE
How is chakra different than Mantine

### ISSUE THREAD

**Issue by capaj** [chakra-ui/chakra-ui-docs#987]
### Subject

How is chakra different than X

### Description

I would love to see How is chakra different than Mantine.

I am mostly chakra-ui dev, but I have tried Mantine recently and I was very interested what do you think are the main differences. To me after 2 days with Mantine it seems to boil down into `sx` vs tailwind-like props.
Like chakra is tailwind for react, but mantine is just another react component package with emotion, which is nice, but I am lacking tailwind props. So I will be certainly sticking to Chakra in the future.

**Comment by rajesh0519** [comment]
I have used chakra in my last project , i like it but some useful components required license ( paid ) . Mantine documentation looks good and easy also free, looking forward to work with it......in my next project.

**Comment by nikolovlazar** [comment]
@rajesh0519 Chakra UI is also free 😅 you don't need to get the Pro product if you don't want to.

**Comment by nikolovlazar** [comment]
@rajesh0519 your comment was not relevant for this issue, so I deleted it.

**Comment by rajesh0519** [comment]
I know its free , but it has some paid components was talking about that,
btw i like using chakra there is nothing wrong with it, was just sharing
opinion 😀

**Comment by nikolovlazar** [comment]
Thank you for your feedback @rajesh0519, but let's do it someplace else 😁

**Comment by rajesh0519** [comment]
I deleted the previous messages and will delete this one too after 10mins ,
will clear all this mess 😀 sorry for the inconvenience, hope u have a nice
day

**Comment by rajesh0519** [comment]
Hope u also delete ur message, let it be clear topic with proper conversation 🙂

**Comment by nikolovlazar** [comment]
I think we should provide comparison docs only for the major frameworks. Writing "How is Chakra UI different than X" docs for most of the frameworks out there would be a very overwhelming task. If you're interested in providing a comparison docs feel free to open a PR and reopen this issue. I'll close this issue for the time being.
